In [ ]:
from google.colab import drive
drive.mount('/content/drive')
db_root = 'drive/MyDrive/camera1_plastics_shareable_dataset'

import pandas as pd
import json

## taxonomy: 15 categories of plastic

In [ ]:
json_file_path = f'{db_root}/camera1_plastics_taxonomy.json'

try:
    with open(json_file_path, 'r') as f:
        data = json.load(f)

    # Assuming the JSON structure is a list of dictionaries or a dictionary of dictionaries
    # If it's a dictionary of dictionaries and you want to treat outer keys as an index or column
    if isinstance(data, dict):
        df = pd.DataFrame.from_dict(data, orient='index')
    elif isinstance(data, list):
        df = pd.DataFrame(data)
    else:
        print("JSON content is not in a recognized format for tabular display (list or dictionary).")
        df = pd.DataFrame([data]) # Try to convert as single row if it's a simple object

    display(df) # Use display for better rendering in Colab
    categories_list = df.loc['categories', 0]
    categories_df = pd.DataFrame(categories_list)
    display(categories_df)
except FileNotFoundError:
    print(f"Error: The file '{json_file_path}' was not found.")
except json.JSONDecodeError:
    print(f"Error: Could not decode JSON from '{json_file_path}'. Check file content.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

,0
dataset,EgoWaste
camera,Camera 1
subset_supercategory,Plastics
number_of_plastic_categories,15
recycle_category_options,[]
categories,"[{'supercategory': 'Plastics', 'name': 'Black ..."


,supercategory,name,abbreviation,recycle_category,description,number_of_instances,number_of_unique_frames,number_of_gx_sequences
0,Plastics,Black Plastic Containers,Black Plastic Containers,Other Plastics,"Plastic containers, whether numbered or unnumb...",251,212,6
1,Plastics,Containers #1/Clamshells,1 Clamshell/ 1,PET (#1)/HDPE (#2) Containers,Plastic containers or lids that are labelled a...,493,410,6
2,Plastics,Containers #2 Colored,2 Colored,PET (#1)/HDPE (#2) Containers,"Plastic containers that are labelled as HDPE, ...",236,206,4
3,Plastics,Containers #2 Natural,2 Natural,PET (#1)/HDPE (#2) Containers,"Plastic containers that are labelled as HDPE, ...",169,137,4
4,Plastics,Containers #3-7 (Not #5),3 to 7,Other Plastic Containers,"Plastic containers that are labeled #3 PVC, #4...",130,107,5
5,Plastics,Containers #5/PP,5,Other Plastic Containers,Plastic containers that are labeled PP (polypr...,386,340,5
6,Plastics,Deposit #1 Bottles,1 Deposit,PET (#1)/HDPE (#2) Containers,"Plastic containers that are labelled as PETE, ...",357,294,5
7,Plastics,Garbage Bags,,Other Plastics,Disposable bag used line trash cans to hold so...,9,9,1
8,Plastics,Non-Deposit,,,,164,137,5
9,Plastics,Other #1 Bottles,1 Other,PET (#1)/HDPE (#2) Containers,"Plastic containers that are labelled as PETE, ...",732,631,5


In [ ]:
pd.set_option('display.max_colwidth', None)
display(categories_df['description'])

,description
0,"Plastic containers, whether numbered or unnumbered, that are colored black. Excludes single-use utensils and non-container plastics."
1,"Plastic containers or lids that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without a screw-off lid."
2,"Plastic containers that are labelled as HDPE, PEHD, or #2 that are pigmented (excluding black)."
3,"Plastic containers that are labelled as HDPE, PEHD, or #2 that are opaque."
4,"Plastic containers that are labeled #3 PVC, #4 LDPE, #6 PS, #7 PLA (excluding #5). Does not include EPS, even if labelled #6."
5,Plastic containers that are labeled PP (polypropylene) or #5.
6,"Plastic containers that are labelled as PETE, PET, or #1 (polyethylene terephthalate) with NY Deposit listed. Must have a screw-off lid."
7,Disposable bag used line trash cans to hold solid waste. Includes bathroom trash bags and contractor bags.
8,
9,"Plastic containers that are labelled as PETE, PET, or #1 (polyethylene terephthalate) without NY Deposit listed. Must have a screw-off lid."


## meta_df: `frames/` & `masks/`

In [ ]:
csv_file_path = f'{db_root}/camera1_plastics_meta2.csv'

try:
    meta_df = pd.read_csv(csv_file_path)
    print(f"Successfully loaded '{csv_file_path}'")
    print("\nFirst 5 rows of the DataFrame:")
    display(meta_df.head())
    print("\nDataFrame Info:")
    display(meta_df.info())
    print("\nDescriptive Statistics:")
    display(meta_df.describe(include='all'))
except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.")
except pd.errors.EmptyDataError:
    print(f"Error: The file '{csv_file_path}' is empty.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

print("--- 'copied_frame_path' 컬럼 분석 ---")
display(meta_df['copied_frame_path'].describe())
print(f"'copied_frame_path' 컬럼의 결측값 수: {meta_df['copied_frame_path'].isnull().sum()}\n")

print("--- 'copied_mask_path' 컬럼 분석 ---")
display(meta_df['copied_mask_path'].describe())
print(f"'copied_mask_path' 컬럼의 결측값 수: {meta_df['copied_mask_path'].isnull().sum()}\n")

print("--- 'timestamp_clip_path' 컬럼 분석 ---")
display(meta_df['timestamp_clip_path'].describe())
print(f"'timestamp_clip_path' 컬럼의 결측값 수: {meta_df['timestamp_clip_path'].isnull().sum()}\n")


Successfully loaded 'drive/MyDrive/camera1_plastics_shareable_dataset/camera1_plastics_meta2.csv'

First 5 rows of the DataFrame:


,data_index,camera_id,gx_id,segment_id,category_name,supercategory_name,recyclable_category_name,reason,phrase,begin_time,...,_source_meta2_path,_gx_name,_camera_name,_original_row_index,frame_name_norm,object_track_id_clean,copied_frame_path,copied_mask_path,timestamp_clip_path,timestamp_transcript_phrases
0,2,1,GX010023,1,Containers #1/Clamshells,Plastics,PET (#1)/HDPE (#2) Containers,Plastic containers or lids that are labelled a...,Clamshell.,12.72,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20...,GX010023,Camera 1,2,18,92,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,NaN
1,3,1,GX010023,1,Containers #1/Clamshells,Plastics,PET (#1)/HDPE (#2) Containers,Plastic containers or lids that are labelled a...,Clamshell.,12.72,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20...,GX010023,Camera 1,3,19,92,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,NaN
2,4,1,GX010023,1,Containers #1/Clamshells,Plastics,PET (#1)/HDPE (#2) Containers,Plastic containers or lids that are labelled a...,Clamshell.,12.72,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20...,GX010023,Camera 1,4,20,92,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,NaN
3,5,1,GX010023,1,Containers #1/Clamshells,Plastics,PET (#1)/HDPE (#2) Containers,Plastic containers or lids that are labelled a...,Clamshell.,12.72,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20...,GX010023,Camera 1,5,21,92,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,NaN
4,6,1,GX010023,1,Containers #1/Clamshells,Plastics,PET (#1)/HDPE (#2) Containers,Plastic containers or lids that are labelled a...,Clamshell.,12.72,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20...,GX010023,Camera 1,6,22,92,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,NaN



DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3538 entries, 0 to 3537
Data columns (total 96 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   data_index                         3538 non-null   int64  
 1   camera_id                          3538 non-null   int64  
 2   gx_id                              3538 non-null   object 
 3   segment_id                         3538 non-null   int64  
 4   category_name                      3538 non-null   object 
 5   supercategory_name                 3538 non-null   object 
 6   recyclable_category_name           3354 non-null   object 
 7   reason                             3354 non-null   object 
 8   phrase                             3538 non-null   object 
 9   begin_time                         1916 non-null   float64
 10  end_time                           1916 non-null   float64
 11  frame_name                         3538

None


Descriptive Statistics:


,data_index,camera_id,gx_id,segment_id,category_name,supercategory_name,recyclable_category_name,reason,phrase,begin_time,...,_source_meta2_path,_gx_name,_camera_name,_original_row_index,frame_name_norm,object_track_id_clean,copied_frame_path,copied_mask_path,timestamp_clip_path,timestamp_transcript_phrases
count,3538.000000,3538.0,3538,3538.000000,3538,3538,3354,3354,3538,1916.000000,...,3538,3538,3538,3538.000000,3538.000000,3538.000000,3538,3534,1916,0.0
unique,NaN,NaN,6,NaN,15,1,3,13,156,NaN,...,6,6,1,NaN,NaN,NaN,3002,3306,463,NaN
top,NaN,NaN,GX020023,NaN,Other #1 Bottles,Plastics,PET (#1)/HDPE (#2) Containers,"Plastic containers that are labelled as PETE, ...",One non -deposit.,NaN,...,/media/jisha/E/trash_dataset/Brookhaven MRF 20...,GX020023,Camera 1,NaN,NaN,NaN,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,/media/jisha/E/trash_dataset/camera1_plastics_...,NaN
freq,NaN,NaN,1150,NaN,732,3538,1987,732,240,NaN,...,1150,1150,3538,NaN,NaN,NaN,4,2,32,NaN
mean,435.413510,1.0,NaN,81.966648,NaN,NaN,NaN,NaN,NaN,533.805538,...,NaN,NaN,NaN,435.413510,900.217637,11211.532504,NaN,NaN,NaN,NaN
std,326.108986,0.0,NaN,60.993272,NaN,NaN,NaN,NaN,NaN,294.200445,...,NaN,NaN,NaN,326.108986,646.490574,8731.674617,NaN,NaN,NaN,NaN
min,0.000000,1.0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,...,NaN,NaN,NaN,0.000000,1.000000,4.000000,NaN,NaN,NaN,NaN
25%,169.250000,1.0,NaN,35.000000,NaN,NaN,NaN,NaN,NaN,274.860000,...,NaN,NaN,NaN,169.250000,369.250000,4359.000000,NaN,NaN,NaN,NaN
50%,358.000000,1.0,NaN,65.000000,NaN,NaN,NaN,NaN,NaN,552.800000,...,NaN,NaN,NaN,358.000000,776.000000,8491.000000,NaN,NaN,NaN,NaN
75%,636.750000,1.0,NaN,119.000000,NaN,NaN,NaN,NaN,NaN,799.920000,...,NaN,NaN,NaN,636.750000,1324.750000,17641.000000,NaN,NaN,NaN,NaN


--- 'copied_frame_path' 컬럼 분석 ---


,copied_frame_path
count,3538
unique,3002
top,/media/jisha/E/trash_dataset/camera1_plastics_...
freq,4


'copied_frame_path' 컬럼의 결측값 수: 0

--- 'copied_mask_path' 컬럼 분석 ---


,copied_mask_path
count,3534
unique,3306
top,/media/jisha/E/trash_dataset/camera1_plastics_...
freq,2


'copied_mask_path' 컬럼의 결측값 수: 4

--- 'timestamp_clip_path' 컬럼 분석 ---


,timestamp_clip_path
count,1916
unique,463
top,/media/jisha/E/trash_dataset/camera1_plastics_...
freq,32


'timestamp_clip_path' 컬럼의 결측값 수: 1622



### Filecheck: all data exists

In [ ]:
import os

def check_paths_in_df(df, column_name, db_root):
    print(f"--- '{column_name}' 컬럼 파일 존재 여부 확인 ---")
    if column_name not in df.columns:
        print(f"Error: Column '{column_name}' not found in DataFrame.")
        return

    unique_paths = df[column_name].dropna().unique()

    if len(unique_paths) == 0:
        print(f"No valid paths found in '{column_name}' to check.")
        return

    # Define the problematic external root and its Colab equivalent
    original_external_root = '/media/jisha/E/trash_dataset/'
    colab_equivalent_prefix = 'drive/MyDrive/'

    all_exist = True
    for path_suffix in unique_paths:
        # Step 1: Replace the old problematic absolute prefix with the new Colab-equivalent one
        if path_suffix.startswith(original_external_root):
            # Replace the external root part. Example: from /media/.../dataset_name/frames to drive/MyDrive/dataset_name/frames
            temp_path_colab_root = path_suffix.replace(original_external_root, colab_equivalent_prefix)
        else:
            # If it doesn't start with the problematic prefix, assume it's already in a potentially correct format
            temp_path_colab_root = path_suffix

        # Step 2: Now, temp_path_colab_root should be like 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/...' or 'frames/...' if already relative.
        # We need to ensure the path is correctly joined with the db_root, which is 'drive/MyDrive/camera1_plastics_shareable_dataset'.
        # The `db_root` variable itself is a relative path to /content/.

        full_path_to_check = None
        # If temp_path_colab_root already contains the db_root structure, extract the relative part
        if temp_path_colab_root.startswith(db_root):
            # e.g., temp_path_colab_root = 'drive/MyDrive/camera1_plastics_shareable_dataset/frames/...'
            # and db_root = 'drive/MyDrive/camera1_plastics_shareable_dataset'
            # We want to check 'db_root/frames/...' so we extract 'frames/...' from temp_path_colab_root
            relative_part_from_db_root = temp_path_colab_root[len(db_root):]
            # Remove leading slash if present for os.path.join
            if relative_part_from_db_root.startswith('/') or relative_part_from_db_root.startswith('\\'):
                relative_part_from_db_root = relative_part_from_db_root[1:]
            full_path_to_check = os.path.join(db_root, relative_part_from_db_root)
        else:
            # If temp_path_colab_root doesn't start with db_root, it might already be the exact path relative to /content/
            # or a path that needs to be directly joined with db_root (e.g. 'frames/GX010023/...' directly)
            full_path_to_check = os.path.join(db_root, temp_path_colab_root)

        # Ensure we are checking a non-empty path
        if not full_path_to_check:
            print(f"Warning: Could not construct a valid path for '{path_suffix}'. Skipping check.")
            all_exist = False
            continue

        if not os.path.exists(full_path_to_check):
            print(f"Warning: File does NOT exist: {full_path_to_check}")
            all_exist = False

    if all_exist:
        print(f"All {len(unique_paths)} unique files in '{column_name}' exist in '{db_root}'.")
    else:
        print(f"Some files in '{column_name}' do NOT exist in '{db_root}'. Please check warnings above.")
    print("\n")

# Check paths for each specified column
check_paths_in_df(meta_df, 'copied_frame_path', db_root)
check_paths_in_df(meta_df, 'copied_mask_path', db_root)
check_paths_in_df(meta_df, 'timestamp_clip_path', db_root)

--- 'copied_frame_path' 컬럼 파일 존재 여부 확인 ---
All 3002 unique files in 'copied_frame_path' exist in 'drive/MyDrive/camera1_plastics_shareable_dataset'.


--- 'copied_mask_path' 컬럼 파일 존재 여부 확인 ---
All 3306 unique files in 'copied_mask_path' exist in 'drive/MyDrive/camera1_plastics_shareable_dataset'.


--- 'timestamp_clip_path' 컬럼 파일 존재 여부 확인 ---
All 463 unique files in 'timestamp_clip_path' exist in 'drive/MyDrive/camera1_plastics_shareable_dataset'.




## Extracting Audio from Video Clips

Now, I will extract the audio from the video files listed in the `timestamp_clip_path` column. The extracted audio files will be saved in the `/content/audio` directory. I'll use `moviepy` for this task.

In [ ]:
# Install moviepy if not already installed
!pip install moviepy

import os
from moviepy.editor import VideoFileClip

# Create the directory for saving audio files if it doesn't exist
audio_output_dir = '/content/audio'
os.makedirs(audio_output_dir, exist_ok=True)
print(f"Audio output directory '{audio_output_dir}' ensured.")

In [ ]:
extracted_audio_info = []

# Set test_limit to an integer (e.g., 5) to process only the first N files.
# Set test_limit = None to process all files in meta_df.
test_limit = None # Change to None to process all files

if test_limit is not None:
    print(f"Processing only the first {test_limit} video clips for audio extraction...")
else:
    print("Processing all video clips for audio extraction...")

# Import tqdm for progress bar
from tqdm.notebook import tqdm

# Iterate through each row of the meta_df DataFrame with tqdm
# For rows where 'timestamp_clip_path' is NaN, we pass None for clip_path
for index, row in tqdm(meta_df.iterrows(), total=len(meta_df) if test_limit is None else test_limit):
    if test_limit is not None and index >= test_limit:
        print(f"Stopped after processing {test_limit} video clips as per test_limit.")
        break

    clip_file_suffix = row['timestamp_clip_path']

    # Only process if clip_file_suffix is not NaN
    if pd.notna(clip_file_suffix):
        # Construct full video path using the established remapping logic
        original_external_root = '/media/jisha/E/trash_dataset/'
        colab_equivalent_prefix = 'drive/MyDrive/'

        if clip_file_suffix.startswith(original_external_root):
            clip_path_temp = clip_file_suffix.replace(original_external_root, colab_equivalent_prefix)
        else:
            clip_path_temp = clip_file_suffix

        if clip_path_temp.startswith(db_root):
            relative_part_clip = clip_path_temp[len(db_root):]
            if relative_part_clip.startswith('/') or relative_part_clip.startswith('\\'):
                relative_part_clip = relative_part_clip[1:]
            full_video_path = os.path.join(db_root, relative_part_clip)
        else:
            full_video_path = os.path.join(db_root, clip_path_temp)

        # Construct output audio file path
        video_basename = os.path.basename(full_video_path)
        audio_filename = os.path.splitext(video_basename)[0] + '.mp3' # or .wav
        output_audio_path = os.path.join(audio_output_dir, audio_filename)

        try:
            if os.path.exists(full_video_path):
                # print(f"Extracting audio from: {full_video_path}") # Suppress this for cleaner tqdm output
                video = VideoFileClip(full_video_path)
                if video.audio is not None:
                    video.audio.write_audiofile(output_audio_path, logger=None) # logger=None to suppress moviepy verbose output
                    extracted_audio_info.append({
                        'original_video_path': full_video_path,
                        'extracted_audio_path': output_audio_path,
                        'status': 'success'
                    })
                    # print(f"Audio saved to: {output_audio_path}") # Suppress this for cleaner tqdm output
                else:
                    extracted_audio_info.append({
                        'original_video_path': full_video_path,
                        'extracted_audio_path': None,
                        'status': 'no_audio_track'
                    })
                    print(f"Warning: No audio track found in {full_video_path}")
                video.close() # Close the video file
            else:
                extracted_audio_info.append({
                    'original_video_path': full_video_path,
                    'extracted_audio_path': None,
                    'status': 'video_not_found'
                })
                print(f"Error: Video file not found: {full_video_path}")

        except Exception as e:
            extracted_audio_info.append({
                'original_video_path': full_video_path,
                'extracted_audio_path': None,
                'status': f'error: {e}'
            })
            print(f"Error extracting audio from {full_video_path}: {e}")
    else:
        # Handle cases where 'timestamp_clip_path' is NaN
        extracted_audio_info.append({
            'original_video_path': None,
            'extracted_audio_path': None,
            'status': 'no_clip_path'
        })

print(f"\nTotal video clips processed for audio extraction: {len(extracted_audio_info)}")
# To see the results, uncomment the line below:
# display(pd.DataFrame(extracted_audio_info).head())

!mv /content/audio /content/drive/MyDrive/csire_code/audio

In [ ]:
!du -hs /content/drive/MyDrive/csire_code/audio

In [ ]:
!ls -al /content/drive/MyDrive/csire_code/audio | wc

### Audio Transcription using Whisper

First, I will install the `openai-whisper` library, which is a state-of-the-art automatic speech recognition (ASR) system. It also requires `torch` for GPU acceleration and `ffmpeg` for audio processing (which should already be available from `moviepy` installation).

In [ ]:
# Install Whisper and other necessary libraries if they aren't already
!pip install -qqq openai-whisper

import os
import json
import pandas as pd
import whisper
from tqdm.notebook import tqdm
from datetime import datetime

print("Whisper and other libraries imported.")

Next, I will define the input and output directories and ensure the output directory for transcriptions exists.

In [ ]:
audio_input_dir = '/content/drive/MyDrive/csire_code/audio'
transcribe_output_dir = '/content/drive/MyDrive/csire_code/transcribe/v1'
manifest_output_path = '/content/drive/MyDrive/csire_code/transcribe/manifest_v1.json'

os.makedirs(transcribe_output_dir, exist_ok=True)
os.makedirs(os.path.dirname(manifest_output_path), exist_ok=True)

print(f"Audio input directory: {audio_input_dir}")
print(f"Transcription output directory: {transcribe_output_dir}")
print(f"Manifest output path: {manifest_output_path}")

Now, I will load the Whisper model (using the 'base' model as a default, but you can change this to 'small', 'medium', or 'large' depending on your needs and available resources). Then, I'll iterate through all audio files in the input directory, transcribe them, and save the results as text files. A manifest file will also be created to log the transcription details.

In [ ]:
# Load the Whisper model
# You can choose 'tiny', 'base', 'small', 'medium', 'large'
# Larger models offer better accuracy but require more VRAM and take longer.
print("Loading Whisper model...")
model = whisper.load_model("base")
print("Whisper model loaded.")

transcription_results = []

# Get list of audio files
audio_files = [f for f in os.listdir(audio_input_dir) if f.endswith('.mp3')]

print(f"Found {len(audio_files)} audio files to transcribe.")

for audio_filename in tqdm(audio_files, desc="Transcribing audio files"):
    audio_file_path = os.path.join(audio_input_dir, audio_filename)
    output_txt_filename = os.path.splitext(audio_filename)[0] + '.txt'
    output_txt_path = os.path.join(transcribe_output_dir, output_txt_filename)

    try:
        # Transcribe the audio
        result = model.transcribe(audio_file_path)
        transcription_text = result["text"]

        # Save the transcription to a text file
        with open(output_txt_path, 'w', encoding='utf-8') as f:
            f.write(transcription_text)

        transcription_results.append({
            'audio_filename': audio_filename,
            'audio_path': audio_file_path,
            'transcription_path': output_txt_path,
            'status': 'success',
            'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
        })
    except Exception as e:
        transcription_results.append({
            'audio_filename': audio_filename,
            'audio_path': audio_file_path,
            'transcription_path': None,
            'status': f'error: {e}',
            'transcription_text_snippet': None
        })
        print(f"Error transcribing {audio_filename}: {e}")

print(f"\nCompleted transcription for {len(transcription_results)} files.")


Finally, I will create a manifest file `manifest_v1.json` containing the details of this transcription run, including the model used, timestamp, and a summary of each transcribed file.

In [ ]:
# Create the manifest file
manifest_data = {
    'run_timestamp': datetime.now().isoformat(),
    'whisper_model': 'base', # Ensure this matches the model used above
    'audio_input_directory': audio_input_dir,
    'transcription_output_directory': transcribe_output_dir,
    'transcription_summary': transcription_results
}

with open(manifest_output_path, 'w', encoding='utf-8') as f:
    json.dump(manifest_data, f, ensure_ascii=False, indent=4)

print(f"Manifest file saved to: {manifest_output_path}")

# Display a snippet of the manifest for verification
print("\nManifest file content (first 5 entries):")
with open(manifest_output_path, 'r', encoding='utf-8') as f:
    manifest_content = json.load(f)
display(pd.DataFrame(manifest_content['transcription_summary']).head())

## 전사 결과와 `camera1_plastics_timestamp_groups.csv` 비교

`camera1_plastics_timestamp_groups.csv` 파일의 정보를 활용하여 Whisper 전사 결과를 비교하려면, 두 데이터 간의 연결 고리를 찾아야 합니다. 일반적으로는 영상 클립의 이름, 시간 정보 또는 고유 ID 등이 연결 고리가 될 수 있습니다.

먼저, `camera1_plastics_timestamp_groups.csv` 파일을 로드하고 그 내용을 살펴보겠습니다.

In [ ]:
timestamp_groups_csv_path = f'{db_root}/camera1_plastics_timestamp_groups.csv'

try:
    timestamp_groups_df = pd.read_csv(timestamp_groups_csv_path)
    print(f"Successfully loaded '{timestamp_groups_csv_path}'")
    print("\nFirst 5 rows of the DataFrame:")
    display(timestamp_groups_df.head())
    print("\nDataFrame Info:")
    display(timestamp_groups_df.info())
    print("\nDescriptive Statistics:")
    display(timestamp_groups_df.describe(include='all'))
except FileNotFoundError:
    print(f"Error: The file '{timestamp_groups_csv_path}' was not found.")
except pd.errors.EmptyDataError:
    print(f"Error: The file '{timestamp_groups_csv_path}' is empty.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

이제 `timestamp_groups_df`를 로드했으니, 이 데이터프레임과 `meta_df`, 그리고 전사 결과를 연결할 수 있는 방법을 찾아야 합니다. `audio_filename`은 `timestamp_clip_path`에서 파생되었으므로, 이 두 컬럼과 `timestamp_groups_df`의 관련 컬럼을 비교하여 연결점을 찾아보겠습니다.

`timestamp_groups_df`의 `clip_path`와 `meta_df`의 `timestamp_clip_path`가 유사한 형식임을 알 수 있습니다. 이들을 매핑하여 전사 결과를 그룹화된 타임스탬프 정보와 연결할 수 있습니다. 예를 들어, 특정 비디오 클립에 대한 전사 내용과 해당 클립의 `phrase`나 `reason` 등을 비교할 수 있습니다.

In [ ]:
import pandas as pd # Ensure pandas is imported if not already in scope
import os # Ensure os is imported if not already in scope

# Ensure meta_df is loaded. This is necessary if previous cells defining it were not run.
csv_file_path = f'{db_root}/camera1_plastics_meta2.csv'
try:
    meta_df = pd.read_csv(csv_file_path)
except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' for meta_df was not found.")
    meta_df = pd.DataFrame() # Create empty DataFrame to avoid further errors
except Exception as e:
    print(f"An unexpected error occurred while loading meta_df: {e}")
    meta_df = pd.DataFrame() # Create empty DataFrame to avoid further errors

# Ensure timestamp_groups_df is loaded. This is necessary if previous cells defining it were not run.
timestamp_groups_csv_path = f'{db_root}/camera1_plastics_timestamp_groups.csv'
try:
    timestamp_groups_df = pd.read_csv(timestamp_groups_csv_path)
except FileNotFoundError:
    print(f"Error: The file '{timestamp_groups_csv_path}' for timestamp_groups_df was not found.")
    timestamp_groups_df = pd.DataFrame() # Create empty DataFrame to avoid further errors
except Exception as e:
    print(f"An unexpected error occurred while loading timestamp_groups_df: {e}")
    timestamp_groups_df = pd.DataFrame() # Create empty DataFrame to avoid further errors


# manifest_v1.json 파일을 다시 로드하는 대신, 이미 메모리에 있는 transcription_results 변수를 사용합니다.
transcription_df = pd.DataFrame(transcription_results)

# 'audio_filename'에서 clip ID를 추출 (예: 'GX010023__000012.720__000014.120.mp3' -> 'GX010023__000012.720__000014.120')
transcription_df['clip_id'] = transcription_df['audio_filename'].apply(lambda x: os.path.splitext(x)[0])

# meta_df의 'timestamp_clip_path'에서 clip ID 추출
# 기존의 remapping 로직을 사용하여 'timestamp_clip_path'를 정규화된 형태로 만든 후 clip ID를 추출합니다.
original_external_root = '/media/jisha/E/trash_dataset/'
colab_equivalent_prefix = 'drive/MyDrive/'

def get_normalized_clip_id(clip_path_suffix):
    if pd.isna(clip_path_suffix): return None

    # Step 1: Replace the old problematic absolute prefix
    if clip_path_suffix.startswith(original_external_root):
        clip_path_temp = clip_path_suffix.replace(original_external_root, colab_equivalent_prefix)
    else:
        clip_path_temp = clip_path_suffix

    # Step 2: Extract the relevant part after db_root (if present) or use as is
    if clip_path_temp.startswith(db_root):
        relative_part_clip = clip_path_temp[len(db_root):]
        if relative_part_clip.startswith('/') or relative_part_clip.startswith('\\'):
            relative_part_clip = relative_part_clip[1:]
        # Now, relative_part_clip should look like 'audio_video_clips/GX010023/GX010023__000012.720__000014.120.mp4'
        # We need to get just the filename part, then remove extension
        return os.path.splitext(os.path.basename(relative_part_clip))[0]
    else:
        # If it doesn't start with db_root, assume it's already a relative path or direct filename
        return os.path.splitext(os.path.basename(clip_path_temp))[0]

meta_df['normalized_clip_id'] = meta_df['timestamp_clip_path'].apply(get_normalized_clip_id)

# timestamp_groups_df의 'clip_path'에서 clip ID 추출
# 'clip_path' 컬럼이 이미 상대 경로 또는 파일 이름 형식일 것이므로, 바로 확장자를 제거합니다.
timestamp_groups_df['clip_id'] = timestamp_groups_df['clip_path'].apply(lambda x: os.path.splitext(os.path.basename(x))[0] if pd.notna(x) else None)


# 이제 transcription_df와 timestamp_groups_df를 'clip_id'를 기준으로 병합하여 비교할 수 있습니다.
# meta_df의 정보를 포함하여 더 풍부한 비교를 할 수도 있습니다.

# transcription_df와 meta_df 병합
merged_transcriptions = pd.merge(
    transcription_df,
    meta_df[['normalized_clip_id', 'phrase', 'reason', 'category_name', 'supercategory_name']],
    left_on='clip_id',
    right_on='normalized_clip_id',
    how='left'
)

# 병합된 결과에 timestamp_groups_df 정보 추가
final_comparison_df = pd.merge(
    merged_transcriptions,
    timestamp_groups_df[['clip_id', 'meta2_phrase', 'begin_time', 'end_time']].rename(columns={'meta2_phrase': 'timestamp_group_phrase'}),
    left_on='clip_id',
    right_on='clip_id',
    how='left'
)

print("\nMerged DataFrame for comparison (first 5 rows):")
display(final_comparison_df.head())

print("\nColumns available for comparison:")
print(final_comparison_df.columns.tolist())

print("\n비교 아이디어:")
print("1. 'transcription_text_snippet'과 'phrase' 또는 'timestamp_group_phrase'를 비교하여 키워드 일치 여부 확인")
print("2. 'category_name', 'supercategory_name'과 'transcription_text_snippet'의 관련성 분석")
print("3. 특정 키워드가 포함된 전사 내용을 기준으로 데이터 필터링")

### 전사 결과와 기존 메타데이터의 'phrase' 비교

이제 `final_comparison_df`를 활용하여 Whisper 전사 (`transcription_text_snippet`) 내용과 `meta_df`의 `phrase` 및 `timestamp_groups_df`의 `timestamp_group_phrase` 간의 일치 여부를 비교해 보겠습니다. 주로 키워드 포함 여부를 확인하는 방식으로 진행합니다.

In [ ]:
# 텍스트 스니펫과 구문 간의 키워드 일치 여부를 확인하는 함수
def check_keyword_match(transcription_text, target_phrase):
    if pd.isna(transcription_text) or pd.isna(target_phrase): return False
    # 소문자로 변환하여 비교하고, 띄어쓰기를 기준으로 단어 분리 (간단한 형태)
    transcription_words = set(transcription_text.lower().split())
    target_words = set(target_phrase.lower().split())

    # 전사된 텍스트의 단어가 target_phrase의 단어에 하나라도 포함되면 True
    return bool(transcription_words.intersection(target_words))

# 'transcription_text_snippet'과 'phrase' 간의 일치 여부 확인
final_comparison_df['matches_meta_phrase'] = final_comparison_df.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)

# 'transcription_text_snippet'과 'timestamp_group_phrase' 간의 일치 여부 확인
final_comparison_df['matches_timestamp_group_phrase'] = final_comparison_df.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['timestamp_group_phrase']),
    axis=1
)

print("키워드 매칭 결과 (상위 10개):")
display(final_comparison_df[['audio_filename', 'transcription_text_snippet', 'phrase', 'matches_meta_phrase', 'timestamp_group_phrase', 'matches_timestamp_group_phrase']].head(10))

print("\n'phrase'와 매칭된 전사 비율:")
print(f"{final_comparison_df['matches_meta_phrase'].sum() / len(final_comparison_df):.2%}")

print("\n'timestamp_group_phrase'와 매칭된 전사 비율:")
print(f"{final_comparison_df['matches_timestamp_group_phrase'].sum() / len(final_comparison_df):.2%}")


### 특정 키워드로 전사 결과 필터링

이제 `final_comparison_df`를 사용하여 특정 키워드를 포함하는 전사 내용을 필터링하고, 해당 클립의 메타데이터 정보를 함께 살펴볼 수 있습니다. 예를 들어, '플라스틱'이라는 단어가 언급된 전사 내용을 찾아보겠습니다.

In [ ]:
keyword_to_filter = 'plastic'

filtered_df = final_comparison_df[
    final_comparison_df['transcription_text_snippet'].str.contains(keyword_to_filter, case=False, na=False)
]

print(f"\n'{keyword_to_filter}' 키워드를 포함하는 전사 결과 (상위 10개):")
display(filtered_df[['audio_filename', 'transcription_text_snippet', 'phrase', 'category_name', 'supercategory_name']].head(10))

print(f"\n총 {len(filtered_df)}개의 전사 결과에서 '{keyword_to_filter}' 키워드가 발견되었습니다.")

이러한 방식으로 전사 결과를 기존 메타데이터와 비교하고 필터링할 수 있습니다. 추가적으로 어떤 종류의 비교나 분석을 원하시나요?

## `timestamp_groups_df` 정보 상세

In [ ]:
timestamp_groups_csv_path = f'{db_root}/camera1_plastics_timestamp_groups.csv'

try:
    timestamp_groups_df = pd.read_csv(timestamp_groups_csv_path)
    print("Timestamp Groups DataFrame (first 5 rows):")
    display(timestamp_groups_df.head())

    print("\nDataFrame Information:")
    display(timestamp_groups_df.info())

    print("\nDescriptive Statistics:")
    display(timestamp_groups_df.describe(include='all'))
except FileNotFoundError:
    print(f"Error: The file '{timestamp_groups_csv_path}' was not found.")
except pd.errors.EmptyDataError:
    print(f"Error: The file '{timestamp_groups_csv_path}' is empty.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

## Whisper 전사 성능 평가

In [ ]:
import pandas as pd
import os

# Ensure db_root is defined
# In a typical Colab environment, this might already be set from an earlier cell
# If not, you might need to run the initial setup cells (e.g., drive mount, db_root definition)

# --- 1. Load meta_df (if not already in kernel state) ---
csv_file_path = f'{db_root}/camera1_plastics_meta2.csv'
try:
    meta_df = pd.read_csv(csv_file_path)
except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' for meta_df was not found.")
    meta_df = pd.DataFrame() # Create empty DataFrame to avoid further errors
except Exception as e:
    print(f"An unexpected error occurred while loading meta_df: {e}")

# Ensure timestamp_groups_df is loaded (if not already in kernel state)
timestamp_groups_csv_path = f'{db_root}/camera1_plastics_timestamp_groups.csv'
try:
    timestamp_groups_df = pd.read_csv(timestamp_groups_csv_path)
except FileNotFoundError:
    print(f"Error: The file '{timestamp_groups_csv_path}' for timestamp_groups_df was not found.")
    timestamp_groups_df = pd.DataFrame() # Create empty DataFrame to avoid further errors
except Exception as e:
    print(f"An unexpected error occurred while loading timestamp_groups_df: {e}")

# --- Diagnostic print: Check supercategory_names in timestamp_groups_df before merge ---
print("\n--- supercategory_names in timestamp_groups_df before merge ---")
if not timestamp_groups_df.empty:
    print(timestamp_groups_df['supercategory_names'].value_counts(dropna=False))
else:
    print("timestamp_groups_df is empty.")


# --- 2. Reconstruct transcription_df from .txt files (if transcription_results not in memory) ---
transcribe_output_dir = '/content/drive/MyDrive/csire_code/transcribe/v1'

if 'transcription_results' not in globals() or not transcription_results:
    print("Reconstructing transcription_results from .txt files...")
    transcription_results = []
    for txt_filename in os.listdir(transcribe_output_dir):
        if txt_filename.endswith('.txt'):
            audio_filename = txt_filename.replace('.txt', '.mp3') # Assuming .mp3 was the original audio format
            audio_path = os.path.join('/content/drive/MyDrive/csire_code/audio', audio_filename)
            transcription_path = os.path.join(transcribe_output_dir, txt_filename)
            try:
                with open(transcription_path, 'r', encoding='utf-8') as f:
                    transcription_text = f.read()
                transcription_results.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': 'success',
                    'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
                })
            except Exception as e:
                print(f"Error reading transcription file {txt_filename}: {e}")
                transcription_results.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': f'error: {e}',
                    'transcription_text_snippet': None
                })
    print(f"Reconstructed {len(transcription_results)} transcription entries.")

transcription_df = pd.DataFrame(transcription_results)

# --- 3. Re-create final_comparison_df with correct merging logic ---

# 'audio_filename'에서 clip ID를 추출 (예: 'GX010023__000012.720__000014.120.mp3' -> 'GX010023__000012.720__000014.120')
transcription_df['clip_id'] = transcription_df['audio_filename'].apply(lambda x: os.path.splitext(x)[0])

# timestamp_groups_df의 'clip_path'에서 clip ID 추출
timestamp_groups_df['clip_id'] = timestamp_groups_df['clip_path'].apply(lambda x: os.path.splitext(os.path.basename(x))[0] if pd.notna(x) else None)

# Merge transcription_df with timestamp_groups_df directly
# This ensures each transcription is associated with the correct clip-level metadata
# and avoids duplicating rows due to frame-level metadata in meta_df.
final_comparison_df = pd.merge(
    transcription_df,
    timestamp_groups_df[['clip_id', 'meta2_phrase', 'category_names', 'supercategory_names', 'begin_time', 'end_time']].rename(columns={
        'meta2_phrase': 'phrase', # Use meta2_phrase from timestamp_groups as the primary phrase
        'supercategory_names': 'supercategory_name' # Rename for consistency
    }),
    left_on='clip_id',
    right_on='clip_id',
    how='left'
)

# --- Diagnostic print: Check supercategory_name in final_comparison_df after merge ---
print("\n--- supercategory_name in final_comparison_df after merge ---")
if not final_comparison_df.empty:
    print(final_comparison_df['supercategory_name'].value_counts(dropna=False))
else:
    print("final_comparison_df is empty.")


# --- 4. Redefine check_keyword_match function ---
def check_keyword_match(transcription_text, target_phrase):
    if pd.isna(transcription_text) or pd.isna(target_phrase): return False
    transcription_words = set(transcription_text.lower().split())
    target_words = set(target_phrase.lower().split())
    return bool(transcription_words.intersection(target_words))

# 'transcription_text_snippet'과 'phrase' 간의 일치 여부 확인
final_comparison_df['matches_meta_phrase'] = final_comparison_df.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)

# For 'timestamp_group_phrase', we'll use the same 'phrase' column for comparison
# as it originates from meta2_phrase in timestamp_groups_df.
final_comparison_df['matches_timestamp_group_phrase'] = final_comparison_df.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)

# --- 5. Performance evaluation code ---
# 전체 'phrase' 및 'timestamp_group_phrase'와의 매칭 비율 재확인
print("\n--- 전체 매칭 비율 ---")
print(f"'phrase'와 매칭된 전사 비율: {final_comparison_df['matches_meta_phrase'].sum() / len(final_comparison_df):.2%}")
print(f"'timestamp_group_phrase'와 매칭된 전사 비율: {final_comparison_df['matches_timestamp_group_phrase'].sum() / len(final_comparison_df):.2%}")

# supercategory_name별 매칭 비율 분석
print("\n--- 'supercategory_name'별 매칭 비율 (phrase) ---")
match_by_supercategory_phrase = final_comparison_df.groupby('supercategory_name')['matches_meta_phrase'].mean().apply(lambda x: f'{x:.2%}')
display(match_by_supercategory_phrase)

print("\n--- 'supercategory_name'별 매칭 비율 (timestamp_group_phrase) ---")
match_by_supercategory_timestamp_phrase = final_comparison_df.groupby('supercategory_name')['matches_timestamp_group_phrase'].mean().apply(lambda x: f'{x:.2%}')
display(match_by_supercategory_timestamp_phrase)

## Whisper V2 (Large 모델) 전사 및 성능 비교

이제 Whisper 'large' 모델을 사용하여 오디오를 다시 전사하고, 이전 'base' 모델(v1)과 성능을 비교해 보겠습니다. 'large' 모델은 더 높은 정확도를 제공할 수 있지만, 전사 시간이 더 오래 걸릴 수 있습니다.

In [ ]:
# Install Whisper and other necessary libraries if they aren't already
!pip install -qqq openai-whisper

import os
import json
import pandas as pd
import whisper
from tqdm.notebook import tqdm
from datetime import datetime

# V2 전사 결과를 위한 디렉토리 설정
transcribe_output_dir_v2 = '/content/drive/MyDrive/csire_code/transcribe/v2'
manifest_output_path_v2 = '/content/drive/MyDrive/csire_code/transcribe/manifest_v2.json'

os.makedirs(transcribe_output_dir_v2, exist_ok=True)
os.makedirs(os.path.dirname(manifest_output_path_v2), exist_ok=True)

# Ensure audio_input_dir and audio_files are defined for this section
audio_input_dir = '/content/drive/MyDrive/csire_code/audio'
audio_files = [f for f in os.listdir(audio_input_dir) if f.endswith('.mp3')]

print(f"V2 Transcription output directory: {transcribe_output_dir_v2}")
print(f"V2 Manifest output path: {manifest_output_path_v2}")
print(f"Audio input directory: {audio_input_dir}")
print(f"Found {len(audio_files)} audio files for V2 transcription.")

In [ ]:
# Whisper 'large' 모델 로드
print("Loading Whisper 'large' model...")
model_large = whisper.load_model("large")
print("Whisper 'large' model loaded.")

transcription_results_v2 = []

# audio_input_dir은 이전 셀에서 정의되었습니다.
# audio_files는 이전 셀에서 로드되었습니다.

print(f"Found {len(audio_files)} audio files to transcribe with V2 (large model).")

# 이 과정은 시간이 오래 걸릴 수 있습니다. 백그라운드 실행을 원하시면 셀을 실행하고 다른 작업을 진행하세요.
for audio_filename in tqdm(audio_files, desc="Transcribing audio files with V2 (large)"):
    audio_file_path = os.path.join(audio_input_dir, audio_filename)
    output_txt_filename = os.path.splitext(audio_filename)[0] + '.txt'
    output_txt_path = os.path.join(transcribe_output_dir_v2, output_txt_filename)

    try:
        # 오디오 전사 (large 모델 사용)
        result = model_large.transcribe(audio_file_path)
        transcription_text = result["text"]

        # 전사 결과를 텍스트 파일로 저장
        with open(output_txt_path, 'w', encoding='utf-8') as f:
            f.write(transcription_text)

        transcription_results_v2.append({
            'audio_filename': audio_filename,
            'audio_path': audio_file_path,
            'transcription_path': output_txt_path,
            'status': 'success',
            'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
        })
    except Exception as e:
        transcription_results_v2.append({
            'audio_filename': audio_filename,
            'audio_path': audio_file_path,
            'transcription_path': None,
            'status': f'error: {e}',
            'transcription_text_snippet': None
        })
        print(f"Error transcribing {audio_filename} with V2: {e}")

print(f"\nCompleted transcription for {len(transcription_results_v2)} files using Whisper V2 (large).")

In [ ]:
# V2 매니페스트 파일 생성
manifest_data_v2 = {
    'run_timestamp': datetime.now().isoformat(),
    'whisper_model': 'large',
    'audio_input_directory': audio_input_dir,
    'transcription_output_directory': transcribe_output_dir_v2,
    'transcription_summary': transcription_results_v2
}

with open(manifest_output_path_v2, 'w', encoding='utf-8') as f:
    json.dump(manifest_data_v2, f, ensure_ascii=False, indent=4)

print(f"V2 Manifest file saved to: {manifest_output_path_v2}")

# V2 매니페스트 내용 일부 표시
print("\nV2 Manifest file content (first 5 entries):")
with open(manifest_output_path_v2, 'r', encoding='utf-8') as f:
    manifest_content_v2 = json.load(f)
display(pd.DataFrame(manifest_content_v2['transcription_summary']).head())

## Whisper V1 (Base) vs V2 (Large) 성능 비교

이제 Whisper 'base' 모델(v1)과 'large' 모델(v2)의 전사 성능을 'supercategory_name'별 매칭률을 기준으로 비교해 보겠습니다.

In [ ]:
import pandas as pd
import os
import json
from tqdm.notebook import tqdm

# db_root와 timestamp_groups_df가 이전 셀에서 정의되었다고 가정합니다.
# 만약 커널 재시작 등으로 인해 정의되지 않았다면, 관련 셀들을 먼저 실행해야 합니다.

# Ensure timestamp_groups_df is loaded. This is necessary if previous cells defining it were not run.
timestamp_groups_csv_path = f'{db_root}/camera1_plastics_timestamp_groups.csv'
try:
    timestamp_groups_df = pd.read_csv(timestamp_groups_csv_path)
    # 'clip_path' 컬럼에서 clip ID 추출
    timestamp_groups_df['clip_id'] = timestamp_groups_df['clip_path'].apply(lambda x: os.path.splitext(os.path.basename(x))[0] if pd.notna(x) else None)
except FileNotFoundError:
    print(f"Error: The file '{timestamp_groups_csv_path}' for timestamp_groups_df was not found.")
    timestamp_groups_df = pd.DataFrame() # Create empty DataFrame to avoid further errors
except Exception as e:
    print(f"An unexpected error occurred while loading timestamp_groups_df: {e}")
    timestamp_groups_df = pd.DataFrame() # Create empty DataFrame to avoid further errors

# --- V1 (Base Model) 데이터프레임 준비 ---
# transcription_results는 이미 메모리에 있다고 가정합니다.
# 만약 없다면, manifest_v1.json에서 로드하거나 .txt 파일에서 재구성합니다.
manifest_output_path_v1 = '/content/drive/MyDrive/csire_code/transcribe/manifest_v1.json'
transcribe_output_dir_v1 = '/content/drive/MyDrive/csire_code/transcribe/v1' # Define V1 output directory

if 'transcription_results' not in globals() or not transcription_results:
    print("Reconstructing V1 transcription_results from .txt files...")
    transcription_results = []
    for txt_filename in tqdm(os.listdir(transcribe_output_dir_v1), desc="Reconstructing V1"): # Added tqdm here
        if txt_filename.endswith('.txt'):
            audio_filename = txt_filename.replace('.txt', '.mp3') # Assuming .mp3 was the original audio format
            audio_path = os.path.join('/content/drive/MyDrive/csire_code/audio', audio_filename)
            transcription_path = os.path.join(transcribe_output_dir_v1, txt_filename)
            try:
                with open(transcription_path, 'r', encoding='utf-8') as f:
                    transcription_text = f.read()
                transcription_results.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': 'success',
                    'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
                })
            except Exception as e:
                print(f"Error reading transcription file {txt_filename}: {e}")
                transcription_results.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': f'error: {e}',
                    'transcription_text_snippet': None
                })
    print(f"Reconstructed {len(transcription_results)} V1 transcription entries.")

transcription_df_v1 = pd.DataFrame(transcription_results)
transcription_df_v1['clip_id'] = transcription_df_v1['audio_filename'].apply(lambda x: os.path.splitext(x)[0])

# timestamp_groups_df는 이 셀 상단에서 로드되었습니다.
# 'clip_id' 컬럼도 생성되었습니다.

final_comparison_df_v1 = pd.merge(
    transcription_df_v1,
    timestamp_groups_df[['clip_id', 'meta2_phrase', 'category_names', 'supercategory_names', 'begin_time', 'end_time']].rename(columns={
        'meta2_phrase': 'phrase',
        'supercategory_names': 'supercategory_name'
    }),
    left_on='clip_id',
    right_on='clip_id',
    how='left'
)

# --- V2 (Large Model) 데이터프레임 준비 ---
# transcription_results_v2는 이미 메모리에 있다고 가정합니다.
# 만약 없다면, manifest_v2.json에서 로드하거나 .txt 파일에서 재구성합니다.
manifest_output_path_v2 = '/content/drive/MyDrive/csire_code/transcribe/manifest_v2.json'
transcribe_output_dir_v2 = '/content/drive/MyDrive/csire_code/transcribe/v2' # Define V2 output directory

if 'transcription_results_v2' not in globals() or not transcription_results_v2:
    print("Reconstructing V2 transcription_results from .txt files...")
    transcription_results_v2 = []
    for txt_filename in tqdm(os.listdir(transcribe_output_dir_v2), desc="Reconstructing V2"): # Added tqdm here
        if txt_filename.endswith('.txt'):
            audio_filename = txt_filename.replace('.txt', '.mp3') # Assuming .mp3 was the original audio format
            audio_path = os.path.join('/content/drive/MyDrive/csire_code/audio', audio_filename)
            transcription_path = os.path.join(transcribe_output_dir_v2, txt_filename)
            try:
                with open(transcription_path, 'r', encoding='utf-8') as f:
                    transcription_text = f.read()
                transcription_results_v2.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': 'success',
                    'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
                })
            except Exception as e:
                print(f"Error reading V2 transcription file {txt_filename}: {e}")
                transcription_results_v2.append({
                    'audio_filename': audio_filename,
                    'audio_path': audio_path,
                    'transcription_path': transcription_path,
                    'status': f'error: {e}',
                    'transcription_text_snippet': None
                })
    print(f"Reconstructed {len(transcription_results_v2)} V2 transcription entries.")

transcription_df_v2 = pd.DataFrame(transcription_results_v2)
transcription_df_v2['clip_id'] = transcription_df_v2['audio_filename'].apply(lambda x: os.path.splitext(x)[0])

final_comparison_df_v2 = pd.merge(
    transcription_df_v2,
    timestamp_groups_df[['clip_id', 'meta2_phrase', 'category_names', 'supercategory_names', 'begin_time', 'end_time']].rename(columns={
        'meta2_phrase': 'phrase',
        'supercategory_names': 'supercategory_name'
    }),
    left_on='clip_id',
    right_on='clip_id',
    how='left'
)

# --- 키워드 매칭 함수 (이전 셀에서 정의된 것을 다시 정의하여 확실히 사용 가능하게 함) ---
def check_keyword_match(transcription_text, target_phrase):
    if pd.isna(transcription_text) or pd.isna(target_phrase): return False
    transcription_words = set(transcription_text.lower().split())
    target_words = set(target_phrase.lower().split())
    return bool(transcription_words.intersection(target_words))

# V1 데이터프레임에 매칭 결과 추가
final_comparison_df_v1['matches_meta_phrase'] = final_comparison_df_v1.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)
final_comparison_df_v1['matches_timestamp_group_phrase'] = final_comparison_df_v1.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)

# V2 데이터프레임에 매칭 결과 추가
final_comparison_df_v2['matches_meta_phrase'] = final_comparison_df_v2.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)
final_comparison_df_v2['matches_timestamp_group_phrase'] = final_comparison_df_v2.apply(
    lambda row: check_keyword_match(row['transcription_text_snippet'], row['phrase']),
    axis=1
)

print("데이터프레임 준비 완료.")

Reconstructing V1 transcription_results from .txt files...


Reconstructing V1:   0%|          | 0/463 [00:00<?, ?it/s]

Reconstructed 463 V1 transcription entries.
Reconstructing V2 transcription_results from .txt files...


Reconstructing V2:   0%|          | 0/463 [00:00<?, ?it/s]

Reconstructed 463 V2 transcription entries.
데이터프레임 준비 완료.


## Whisper V1 (Base) vs V2 (Large) Success Rate Comparison

In [ ]:
print("\n--- Overall Matching Rate Comparison ---")
print(f"V1 (Base) 'phrase' matching rate: {final_comparison_df_v1['matches_meta_phrase'].sum() / len(final_comparison_df_v1):.2%}")
print(f"V2 (Large) 'phrase' matching rate: {final_comparison_df_v2['matches_meta_phrase'].sum() / len(final_comparison_df_v2):.2%}")

print("\n--- 'supercategory_name' Matching Rate (V1 Base) ---")
match_by_supercategory_phrase_v1 = final_comparison_df_v1.groupby('supercategory_name')['matches_meta_phrase'].mean().apply(lambda x: f'{x:.2%}')
display(match_by_supercategory_phrase_v1)

print("\n--- 'supercategory_name' Matching Rate (V2 Large) ---")
match_by_supercategory_phrase_v2 = final_comparison_df_v2.groupby('supercategory_name')['matches_meta_phrase'].mean().apply(lambda x: f'{x:.2%}')
display(match_by_supercategory_phrase_v2)

## Phrase Value Counts per Category

In [ ]:
phrase_counts_by_category = timestamp_groups_df.groupby('category_names')['meta2_phrase'].nunique()
for category in timestamp_groups_df['category_names'].unique():
    print(f"\n--- Category: {category}: {phrase_counts_by_category[category]} ---")
    category_phrases = timestamp_groups_df[timestamp_groups_df['category_names'] == category]['meta2_phrase'].value_counts().to_dict()
    for phrase, count in category_phrases.items():
        print(f"  '{phrase}': {count}")

### Validating `map_transcript_to_category` function using `timestamp_groups_df['meta2_phrase']`

We will compare the `predicted_category` with the actual `category_name`.

In [ ]:
def map_transcript_to_category(transcript_text):
    if pd.isna(transcript_text): return "Unknown"
    text = transcript_text.lower()

    # --- 1. Exact Matches (Highest Priority) ---
    # These are highly specific phrases that should map to a single, confident category.
    if text == "non -deposit garbage bag":
        return "Non-Deposit" # Fix for common misclassification (Actual: Non-Deposit, Predicted: Garbage Bags)
    if text == "dissolt.":
        return "Deposit #1 Bottles"
    if text == "fly plastic.":
        return "Black Plastic Containers"
    if text == "under posit one down to positive":
        return "Non-Deposit"
    if text == "no." or text == "no":
        return "Containers #1/Clamshells"
    if text == "one deposit." or text == "one deposit":
        return "Deposit #1 Bottles"
    if "other one" in text or "lid" in text:
        return "Containers #1/Clamshells"
    if "five" in text or "5" in text:
        return "Containers #5/PP"
    if text == "unnumbered.":
        return "Other Unnumbered Containers & Fragments"
    if text == "other plastic.":
        return "Other Plastics"
    if "two" in text and "color" in text:
        return "Containers #2 Colored"
    if text == "number one.":
        return "Deposit #1 Bottles" # Assuming "number one." alone usually means Deposit #1 Bottles based on phrase_counts_by_category

    # --- 2. Highly Specific Keyword-Based Rules (Higher Priority) ---
    # NEW RULE: If both "one" and "non" are present, classify as "Other #1 Bottles"
    if ("one" in text or "1" in text) and "non" in text:
        return "Other #1 Bottles"

    if "non" in text and "deposit" in text:
        return "Non-Deposit"

    # These cover phrases containing strong category indicators.
    if "garbage bag" in text:
        return "Garbage Bags"

    if "black" in text:
        return "Black Plastic Containers"

    if "clam" in text and "shell" in text:
        return "Containers #1/Clamshells"

    if "two natural" in text:
        return "Containers #2 Natural"
    if "two color" in text or "two colored" in text:
        return "Containers #2 Colored"

    # --- 3. Number-Based Rules (Medium Priority) ---
    if "three" in text or "3" in text or "seven" in text or "7" in text or "four" in text or "4" in text or "six" in text or "6" in text:
        return "Containers #3-7 (Not #5)"
    if "five" in text or "5" in text:
        return "Containers #5/PP"

    # --- 4. Deposit/Non-Deposit & Number #1 Rules (Careful Prioritization) ---
    # This section is critical for distinguishing similar phrases.
    if "number one" in text:
        if "deposit" in text:
            return "Deposit #1 Bottles"
        # The 'non -deposit' case here for 'number one' will be caught by the new 'one' and 'non' rule if 'non' is also present
        return "Other #1 Bottles" # If 'number one' but no deposit/non-deposit specifier (and not caught by 'one' and 'non' rule)

    if "deposit" in text:
        return "Deposit #1 Bottles"


    # --- 5. Other Generic Category Keywords (Lower Priority) ---
    if "plastic film" in text or "film plastic" in text or "film" in text:
        return "Other Plastic Film"

    if "other plastic" in text:
        return "Other Plastics"

    if "unnumbered" in text:
        return "Other Unnumbered Containers & Fragments"

    if "bulky rigid" in text:
        return "Other Rigid/Bulky Plastics"

    if "if you find numbers" in text:
        return "Other Unnumbered Containers & Fragments"

    if "plastic" in text:
        return "Plastic"

    if "one" in text:
        return "Containers #1/Clamshells"
    # Default return if no rules match
    return "Unknown"

# Apply the mapping function to timestamp_groups_df['meta2_phrase']
timestamp_groups_df['predicted_category_from_phrase'] = timestamp_groups_df['meta2_phrase'].apply(map_transcript_to_category)

# Calculate the success rate
success_rate_from_phrase = (timestamp_groups_df['predicted_category_from_phrase'] == timestamp_groups_df['category_names']).mean() * 100

print(f"Success Rate of `map_transcript_to_category` using `timestamp_groups_df['meta2_phrase']`: {success_rate_from_phrase:.2f}%")

# Identify misclassified entries
incorrect_classifications = timestamp_groups_df[
    timestamp_groups_df['predicted_category_from_phrase'] != timestamp_groups_df['category_names']
]

# Group by actual category, predicted category, and phrase to find common misclassification patterns
misclassification_patterns = incorrect_classifications.groupby(['meta2_phrase', 'category_names', 'predicted_category_from_phrase']).size().reset_index(name='count')

# Sort by count to see the most frequent misclassifications
misclassification_patterns = misclassification_patterns.sort_values(by='count', ascending=False)

print("\nMost Frequent Misclassification Patterns (Top 20):")
display(misclassification_patterns.head(30))

print(f"\nTotal misclassified entries: {len(incorrect_classifications)}")

Success Rate of `map_transcript_to_category` using `timestamp_groups_df['meta2_phrase']`: 91.14%

Most Frequent Misclassification Patterns (Top 20):


,meta2_phrase,category_names,predicted_category_from_phrase,count
12,"Non -deposit,",Other #1 Bottles,Non-Deposit,2
0,A number.,Other Unnumbered Containers & Fragments,Unknown,1
2,Deposit aluminum container or film.,Other Plastic Film,Deposit #1 Bottles,1
1,Clam,Containers #1/Clamshells,Unknown,1
4,Film plastic.,Other Plastic Film | Other Plastics,Other Plastic Film,1
5,It doesn't have number.,Other Unnumbered Containers & Fragments,Unknown,1
6,It says one right there.,Other #1 Bottles,Containers #1/Clamshells,1
3,Deposit.,Other #1 Bottles,Deposit #1 Bottles,1
7,It's light purple.,Containers #2 Colored,Unknown,1
8,Just a number.,Other Unnumbered Containers & Fragments,Unknown,1



Total misclassified entries: 41


In [ ]:
print("\n--- Overall Matching Rate Comparison (using map_transcript_to_category) ---")

# V1 (Base Model) - Apply map_transcript_to_category
final_comparison_df_v1['predicted_category'] = final_comparison_df_v1['transcription_text_snippet'].apply(map_transcript_to_category)
success_rate_v1 = (final_comparison_df_v1['predicted_category'] == final_comparison_df_v1['category_names']).mean() * 100
print(f"V1 (Base) 'map_transcript_to_category' success rate: {success_rate_v1:.2f}%")

# V2 (Large Model) - Apply map_transcript_to_category
final_comparison_df_v2['predicted_category'] = final_comparison_df_v2['transcription_text_snippet'].apply(map_transcript_to_category)
success_rate_v2 = (final_comparison_df_v2['predicted_category'] == final_comparison_df_v2['category_names']).mean() * 100
print(f"V2 (Large) 'map_transcript_to_category' success rate: {success_rate_v2:.2f}%")

print("\n--- 'supercategory_name'별 매칭 비율 (map_transcript_to_category) 비교 ---")
print("V1 (Base) 모델:")
match_by_supercategory_v1 = final_comparison_df_v1.groupby('supercategory_name')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v1.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_supercategory_v1)

print("V2 (Large) 모델:")
match_by_supercategory_v2 = final_comparison_df_v2.groupby('supercategory_name')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v2.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_supercategory_v2)


print("\n--- 'category_name'별 매칭 비율 (map_transcript_to_category) 비교 ---")
print("V1 (Base) 모델:")
match_by_category_v1 = final_comparison_df_v1.groupby('category_names')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v1.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_category_v1)

print("V2 (Large) 모델:")
match_by_category_v2 = final_comparison_df_v2.groupby('category_names')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v2.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_category_v2)


--- Overall Matching Rate Comparison (using map_transcript_to_category) ---
V1 (Base) 'map_transcript_to_category' success rate: 28.73%
V2 (Large) 'map_transcript_to_category' success rate: 60.48%

--- 'supercategory_name'별 매칭 비율 (map_transcript_to_category) 비교 ---
V1 (Base) 모델:


,predicted_category
supercategory_name,
Plastics,28.73%


V2 (Large) 모델:


,predicted_category
supercategory_name,
Plastics,60.48%



--- 'category_name'별 매칭 비율 (map_transcript_to_category) 비교 ---
V1 (Base) 모델:


,predicted_category
category_names,
Black Plastic Containers,19.44%
Black Plastic Containers | Other Unnumbered Containers & Fragments,0.00%
Containers #1/Clamshells,22.54%
Containers #1/Clamshells | Garbage Bags,0.00%
Containers #2 Colored,26.32%
Containers #2 Colored | Deposit #1 Bottles,0.00%
Containers #2 Colored | Other #1 Bottles,0.00%
Containers #2 Natural,18.75%
Containers #3-7 (Not #5),61.54%


V2 (Large) 모델:


,predicted_category
category_names,
Black Plastic Containers,80.56%
Black Plastic Containers | Other Unnumbered Containers & Fragments,0.00%
Containers #1/Clamshells,64.79%
Containers #1/Clamshells | Garbage Bags,0.00%
Containers #2 Colored,73.68%
Containers #2 Colored | Deposit #1 Bottles,0.00%
Containers #2 Colored | Other #1 Bottles,0.00%
Containers #2 Natural,6.25%
Containers #3-7 (Not #5),53.85%


In [ ]:
# Calculate success rates for V1 by category_name
success_by_category_v1 = final_comparison_df_v1.groupby('category_names')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v1.loc[x.index, 'category_names']).mean() * 100
).reset_index()
success_by_category_v1.rename(columns={'predicted_category': 'predicted_category_v1_success_rate'}, inplace=True)

# Calculate success rates for V2 by category_name
success_by_category_v2 = final_comparison_df_v2.groupby('category_names')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v2.loc[x.index, 'category_names']).mean() * 100
).reset_index()
success_by_category_v2.rename(columns={'predicted_category': 'predicted_category_v2_success_rate'}, inplace=True)

# Calculate success rates for 'predicted_category_from_phrase' (ground truth phrase mapping) using timestamp_groups_df
success_by_category_from_phrase = timestamp_groups_df.groupby('category_names')['predicted_category_from_phrase'].apply(
    lambda x: (x == timestamp_groups_df.loc[x.index, 'category_names']).mean() * 100
).reset_index()
success_by_category_from_phrase.rename(columns={'predicted_category_from_phrase': 'predicted_category_from_phrase_success_rate'}, inplace=True)

# Merge all success rates into a single DataFrame
comparison_success_rates = pd.merge(success_by_category_v1, success_by_category_v2, on='category_names', how='outer')
comparison_success_rates = pd.merge(comparison_success_rates, success_by_category_from_phrase, on='category_names', how='outer')

import os

# Ensure timestamp_groups_df has 'clip_id' column for this calculation
# This line might be redundant if the column is created earlier and guaranteed to persist,
# but adding it here ensures the calculation always works.
if 'clip_id' not in timestamp_groups_df.columns:
    timestamp_groups_df['clip_id'] = timestamp_groups_df['clip_path'].apply(lambda x: os.path.splitext(os.path.basename(x))[0] if pd.notna(x) else None)

total_clips_by_category = timestamp_groups_df.groupby('category_names')['clip_id'].nunique().reset_index()
total_clips_by_category.rename(columns={'clip_id': 'total_clips'}, inplace=True)

final_comparison_summary = pd.merge(comparison_success_rates, total_clips_by_category, on='category_names', how='outer')

overall_success_v1 = success_rate_v1
overall_success_v2 = success_rate_v2
overall_success_from_phrase = success_rate_from_phrase

overall_total_clips = total_clips_by_category['total_clips'].sum()

overall_summary_row = pd.DataFrame([{
    'category_names': 'Overall',
    'predicted_category_v1_success_rate': overall_success_v1,
    'predicted_category_v2_success_rate': overall_success_v2,
    'predicted_category_from_phrase_success_rate': overall_success_from_phrase,
    'total_clips': overall_total_clips
}])

final_comparison_summary_with_overall = pd.concat([final_comparison_summary, overall_summary_row], ignore_index=True)

print("\nCombined Category-wise Success Rates and Total Clips (with Overall Summary):")
display(final_comparison_summary_with_overall.sort_values(by='total_clips', ascending=False).round(2))


Combined Category-wise Success Rates and Total Clips (with Overall Summary):


,category_names,predicted_category_v1_success_rate,predicted_category_v2_success_rate,predicted_category_from_phrase_success_rate,total_clips
20,Overall,28.73,60.48,91.14,463
13,Other #1 Bottles,22.22,56.79,88.89,81
2,Containers #1/Clamshells,22.54,64.79,91.55,71
9,Containers #5/PP,60.71,85.71,100.00,56
10,Deposit #1 Bottles,30.91,69.09,92.73,55
18,Other Unnumbered Containers & Fragments,36.96,71.74,91.30,46
16,Other Plastics,19.44,38.89,100.00,36
0,Black Plastic Containers,19.44,80.56,97.22,36
4,Containers #2 Colored,26.32,73.68,94.74,19
12,Non-Deposit,5.56,5.56,88.89,18


## Semantic retrieval

### Step 1: Load Common Phrases and Install Semantic Embedding Library

First, we will load the `camera1_plastics_common_phrases.csv` file to get the `normalized_phrase` and `example_categories`. Then, we'll install `sentence-transformers` to generate embeddings for semantic similarity.

In [ ]:
# Install sentence-transformers if not already installed
!pip install -qqq sentence-transformers

import pandas as pd
from sentence_transformers import SentenceTransformer, util
import numpy as np
import json
import os

# Load the common phrases CSV file
common_phrases_csv_path = f'{db_root}/camera1_plastics_common_phrases.csv'

try:
    common_phrases_df = pd.read_csv(common_phrases_csv_path)
    print(f"Successfully loaded '{common_phrases_csv_path}'")
    print("\nFirst 5 rows of common_phrases_df:")
    display(common_phrases_df.head())
    print("\nDataFrame Info of common_phrases_df:")
    display(common_phrases_df.info())
except FileNotFoundError:
    print(f"Error: The file '{common_phrases_csv_path}' was not found.")
    common_phrases_df = pd.DataFrame() # Create empty DataFrame
except Exception as e:
    print(f"An unexpected error occurred while loading common_phrases_df: {e}")
    common_phrases_df = pd.DataFrame() # Create empty DataFrame

# Preprocess 'example_categories' if it's a string representation of a list
if 'example_categories' in common_phrases_df.columns:
    # Attempt to parse strings that look like lists, otherwise keep as is
    common_phrases_df['parsed_categories'] = common_phrases_df['example_categories'].apply(
        lambda x: json.loads(x.replace("'", '"')) if isinstance(x, str) and x.startswith('[') else x
    )
    # If it's a list, take the first element; otherwise, use the value directly
    common_phrases_df['target_category'] = common_phrases_df['parsed_categories'].apply(
        lambda x: x[0] if isinstance(x, list) and x else (x if x is not None else None)
    )
else:
    common_phrases_df['target_category'] = None

# Drop rows where target_category is None
common_phrases_df.dropna(subset=['normalized_phrase', 'target_category'], inplace=True)

print("\nProcessed common_phrases_df (first 5 rows with target_category):")
display(common_phrases_df[['normalized_phrase', 'target_category']].head())

Successfully loaded 'drive/MyDrive/camera1_plastics_shareable_dataset/camera1_plastics_common_phrases.csv'

First 5 rows of common_phrases_df:


,rank,normalized_phrase,representative_phrase,count,source_types,example_gx,example_categories,example_clip_path
0,1,clamshell,Clamshell.,43,meta2,GX010023,Containers #1/Clamshells,/media/jisha/E/trash_dataset/camera1_plastics_...
1,2,one non -deposit,One non -deposit.,36,meta2,GX010023,Other #1 Bottles,/media/jisha/E/trash_dataset/camera1_plastics_...
2,3,other plastic,Other plastic.,36,meta2,GX010023,Other Plastics,/media/jisha/E/trash_dataset/camera1_plastics_...
3,4,unnumbered,Unnumbered.,36,meta2,GX010023,Other Unnumbered Containers & Fragments,/media/jisha/E/trash_dataset/camera1_plastics_...
4,5,black plastic,Black plastic.,32,meta2,GX010023,Black Plastic Containers,/media/jisha/E/trash_dataset/camera1_plastics_...



DataFrame Info of common_phrases_df:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   rank                   104 non-null    int64 
 1   normalized_phrase      104 non-null    object
 2   representative_phrase  104 non-null    object
 3   count                  104 non-null    int64 
 4   source_types           104 non-null    object
 5   example_gx             104 non-null    object
 6   example_categories     104 non-null    object
 7   example_clip_path      104 non-null    object
dtypes: int64(2), object(6)
memory usage: 6.6+ KB


None


Processed common_phrases_df (first 5 rows with target_category):


,normalized_phrase,target_category
0,clamshell,Containers #1/Clamshells
1,one non -deposit,Other #1 Bottles
2,other plastic,Other Plastics
3,unnumbered,Other Unnumbered Containers & Fragments
4,black plastic,Black Plastic Containers


### Step 2: Load Sentence Transformer Model and Generate Embeddings

Next, we'll load a pre-trained `SentenceTransformer` model (e.g., `all-MiniLM-L6-v2`) and generate embeddings for the `normalized_phrase` values from `common_phrases_df`. These embeddings will serve as our reference for semantic comparison.

In [ ]:
# Load a pre-trained Sentence Transformer model
print("Loading Sentence Transformer model...")
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Sentence Transformer model loaded.")

# Generate embeddings for the normalized phrases
print("Generating embeddings for common phrases...")
common_phrase_embeddings = embedding_model.encode(common_phrases_df['normalized_phrase'].tolist(), convert_to_tensor=True)
print(f"Generated {len(common_phrase_embeddings)} embeddings for common phrases.")

Loading Sentence Transformer model...


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Sentence Transformer model loaded.
Generating embeddings for common phrases...
Generated 104 embeddings for common phrases.


### Step 3: Implement Semantic Retrieval Function

Now, we'll define a function that takes a transcription text, generates its embedding, and then finds the `normalized_phrase` from our `common_phrases_df` that is most semantically similar. This will allow us to predict a `category_name` based on semantic context.

In [ ]:
def get_semantic_category(transcript_text, top_k=1):
    if pd.isna(transcript_text) or not isinstance(transcript_text, str):
        return "Unknown"

    # Generate embedding for the transcription text
    transcript_embedding = embedding_model.encode(transcript_text, convert_to_tensor=True)

    # Calculate cosine similarity between the transcript embedding and all common phrase embeddings
    cosine_scores = util.cos_sim(transcript_embedding, common_phrase_embeddings)[0]

    # Get the top_k most similar phrases
    top_results = np.argpartition(-cosine_scores.cpu().numpy(), top_k)[:top_k]

    # Retrieve the category from the most similar phrase
    if len(top_results) > 0:
        best_match_idx = top_results[0] # Take the top result
        return common_phrases_df.iloc[best_match_idx]['target_category']
    else:
        return "Unknown"

print("Semantic retrieval function `get_semantic_category` defined.")

Semantic retrieval function `get_semantic_category` defined.


### Step 4: Apply Semantic Retrieval and Evaluate Performance

Finally, we'll apply our `get_semantic_category` function to the V2 (Large model) transcriptions in `final_comparison_df_v2` and evaluate its success rate against the actual `category_names`.

In [ ]:
print("Applying semantic retrieval to V2 transcriptions...")
# Apply the semantic mapping function to V2 transcriptions
final_comparison_df_v2['predicted_category_semantic'] = final_comparison_df_v2['transcription_text_snippet'].apply(get_semantic_category)

# Calculate the overall success rate for semantic retrieval (V2)
semantic_success_rate_v2 = (final_comparison_df_v2['predicted_category_semantic'] == final_comparison_df_v2['category_names']).mean() * 100

print(f"\nV2 (Large) Semantic Retrieval success rate: {semantic_success_rate_v2:.2f}%")

print("\n--- 'supercategory_name'별 매칭 비율 (Semantic Retrieval) --- ")
match_by_supercategory_semantic_v2 = final_comparison_df_v2.groupby('supercategory_name')['predicted_category_semantic'].apply(
    lambda x: (x == final_comparison_df_v2.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_supercategory_semantic_v2)

print("\n--- 'category_name'별 매칭 비율 (Semantic Retrieval) --- ")
match_by_category_semantic_v2 = final_comparison_df_v2.groupby('category_names')['predicted_category_semantic'].apply(
    lambda x: (x == final_comparison_df_v2.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')
display(match_by_category_semantic_v2)


# Display a sample of semantic predictions
print("\nSample of V2 Semantic Predictions (first 10 rows):")
display(final_comparison_df_v2[[
    'audio_filename',
    'transcription_text_snippet',
    'phrase', # This is the ground truth phrase from meta2
    'category_names', # This is the actual category
    'predicted_category_semantic' # This is the category predicted by semantic retrieval
]].head(10))

Applying semantic retrieval to V2 transcriptions...

V2 (Large) Semantic Retrieval success rate: 66.52%

--- 'supercategory_name'별 매칭 비율 (Semantic Retrieval) --- 


,predicted_category_semantic
supercategory_name,
Plastics,66.52%



--- 'category_name'별 매칭 비율 (Semantic Retrieval) --- 


,predicted_category_semantic
category_names,
Black Plastic Containers,69.44%
Black Plastic Containers | Other Unnumbered Containers & Fragments,100.00%
Containers #1/Clamshells,80.28%
Containers #1/Clamshells | Garbage Bags,100.00%
Containers #2 Colored,63.16%
Containers #2 Colored | Deposit #1 Bottles,100.00%
Containers #2 Colored | Other #1 Bottles,50.00%
Containers #2 Natural,62.50%
Containers #3-7 (Not #5),76.92%



Sample of V2 Semantic Predictions (first 10 rows):


,audio_filename,transcription_text_snippet,phrase,category_names,predicted_category_semantic
0,GX010023__000674.320__000676.680.mp3,If it has like a like a lid that you can scre...,Like a lid that you can screw on,Deposit #1 Bottles,Other #1 Bottles
1,GX010023__000759.020__000760.380.mp3,I'm all thrown off. Deposit number one. I nee...,"Deposit number one,",Deposit #1 Bottles,Deposit #1 Bottles
2,GX010023__000823.900__000825.160.mp3,deposit number one,Deposit number one.,Deposit #1 Bottles,Deposit #1 Bottles
3,GX010023__000984.360__000984.860.mp3,"one non deposit, one deposit oh my god",one deposit.,Deposit #1 Bottles,Other #1 Bottles
4,GX010023__000063.320__000063.860.mp3,Deposit? Not a deposit. I'm pretty sure.,Non -deposit.,Non-Deposit,Deposit #1 Bottles
5,GX010023__000171.640__000172.400.mp3,film plastic,Other non -deposit.,Non-Deposit,Other Plastic Film | Other Plastics
6,GX010023__000176.260__000177.480.mp3,clamshell,Other non -deposit.,Non-Deposit,Containers #1/Clamshells
7,GX010023__000618.600__000620.480.mp3,Cleaner water? Black plastic Although none of...,Other non -deposit,Non-Deposit,Containers #2 Colored | Deposit #1 Bottles
8,GX010023__000730.540__000733.840.mp3,,Other non -deposited,Non-Deposit,Containers #1/Clamshells
9,GX010023__001002.280__001003.320.mp3,Found a posit Found a posit,Non -deposit.,Non-Deposit,Non-Deposit


### Comparison of V1, V2, and `meta2_phrase` Category Prediction Performance

This table summarizes the success rates for category prediction across different models and methods:
- `predicted_category_v1_success_rate`: Success rate using Whisper V1 (Base) transcriptions with `map_transcript_to_category`.
- `predicted_category_v2_success_rate`: Success rate using Whisper V2 (Large) transcriptions with `map_transcript_to_category`.
- `predicted_category_from_phrase_success_rate`: Success rate using the `meta2_phrase` directly with `map_transcript_to_category` (serving as a near-perfect baseline for the rule-based mapping).
- `predicted_category_semantic_success_rate`: Success rate using Whisper V2 (Large) transcriptions with the semantic retrieval method.


In [ ]:
# Merge semantic success rate into the comparison summary
comparison_success_rates_with_semantic = pd.merge(
    final_comparison_summary,
    match_by_category_semantic_v2.rename('predicted_category_semantic_success_rate').reset_index(),
    on='category_names',
    how='left'
)

# Ensure total_clips is included by re-merging with total_clips_by_category
final_comparison_summary_complete = pd.merge(
    comparison_success_rates_with_semantic,
    total_clips_by_category,
    on='category_names',
    how='outer'
)

# Prepare overall semantic success rate row
overall_semantic_summary_row = pd.DataFrame([{
    'category_names': 'Overall',
    'predicted_category_v1_success_rate': overall_success_v1,
    'predicted_category_v2_success_rate': overall_success_v2,
    'predicted_category_from_phrase_success_rate': overall_success_from_phrase,
    'predicted_category_semantic_success_rate': semantic_success_rate_v2, # Use the overall semantic rate
    'total_clips': overall_total_clips
}])

# Concatenate overall row to the complete summary
final_comparison_summary_final = pd.concat([
    final_comparison_summary_complete,
    overall_semantic_summary_row
], ignore_index=True)

# Display the final comparison summary with all metrics
print("\nCombined Category-wise Success Rates and Total Clips (with Overall Summary):")
display(final_comparison_summary_final.sort_values(by='total_clips', ascending=False).round(2))


Combined Category-wise Success Rates and Total Clips (with Overall Summary):


,category_names,predicted_category_v1_success_rate,predicted_category_v2_success_rate,predicted_category_from_phrase_success_rate,total_clips_x,predicted_category_semantic_success_rate,total_clips_y,total_clips
20,Overall,28.73,60.48,91.14,NaN,66.522678,NaN,463.0
0,Black Plastic Containers,19.44,80.56,97.22,36.0,69.44%,36.0,NaN
1,Black Plastic Containers | Other Unnumbered Co...,0.00,0.00,0.00,1.0,100.00%,1.0,NaN
2,Containers #1/Clamshells,22.54,64.79,91.55,71.0,80.28%,71.0,NaN
3,Containers #1/Clamshells | Garbage Bags,0.00,0.00,0.00,1.0,100.00%,1.0,NaN
4,Containers #2 Colored,26.32,73.68,94.74,19.0,63.16%,19.0,NaN
5,Containers #2 Colored | Deposit #1 Bottles,0.00,0.00,0.00,1.0,100.00%,1.0,NaN
6,Containers #2 Colored | Other #1 Bottles,0.00,0.00,0.00,2.0,50.00%,2.0,NaN
7,Containers #2 Natural,18.75,6.25,75.00,16.0,62.50%,16.0,NaN
8,Containers #3-7 (Not #5),61.54,53.85,100.00,13.0,76.92%,13.0,NaN


In [ ]:
print("Comparison of V2 Rule-Based vs. V2 Semantic Retrieval Success Rates:")
comparison_df = final_comparison_summary_final[[
    'category_names',
    'predicted_category_v2_success_rate',
    'predicted_category_semantic_success_rate',
    'total_clips'
]].sort_values(by='total_clips', ascending=False).round(2)
display(comparison_df)

overall_v2_rule_based = final_comparison_summary_final[final_comparison_summary_final['category_names'] == 'Overall']['predicted_category_v2_success_rate'].iloc[0]
overall_v2_semantic = final_comparison_summary_final[final_comparison_summary_final['category_names'] == 'Overall']['predicted_category_semantic_success_rate'].iloc[0]

if overall_v2_rule_based == overall_v2_semantic:
    print(f"\nVerdict: The overall success rates for V2 rule-based ({overall_v2_rule_based:.2f}%) and V2 semantic retrieval ({overall_v2_semantic:.2f}%) are the same.")
else:
    print(f"\nVerdict: The overall success rates for V2 rule-based ({overall_v2_rule_based:.2f}%) and V2 semantic retrieval ({overall_v2_semantic:.2f}%) are different. Semantic retrieval has a higher success rate.")


Comparison of V2 Rule-Based vs. V2 Semantic Retrieval Success Rates:


,category_names,predicted_category_v2_success_rate,predicted_category_semantic_success_rate,total_clips
20,Overall,60.48,66.522678,463.0
0,Black Plastic Containers,80.56,69.44%,NaN
1,Black Plastic Containers | Other Unnumbered Co...,0.00,100.00%,NaN
2,Containers #1/Clamshells,64.79,80.28%,NaN
3,Containers #1/Clamshells | Garbage Bags,0.00,100.00%,NaN
4,Containers #2 Colored,73.68,63.16%,NaN
5,Containers #2 Colored | Deposit #1 Bottles,0.00,100.00%,NaN
6,Containers #2 Colored | Other #1 Bottles,0.00,50.00%,NaN
7,Containers #2 Natural,6.25,62.50%,NaN
8,Containers #3-7 (Not #5),53.85,76.92%,NaN



Verdict: The overall success rates for V2 rule-based (60.48%) and V2 semantic retrieval (66.52%) are different. Semantic retrieval has a higher success rate.


### Re-comparison of V1, V2, and `meta2_phrase` Performance

In [ ]:
print("Combined Category-wise Success Rates and Total Clips (with Overall Summary):")
display(final_comparison_summary_final.sort_values(by='total_clips', ascending=False).round(2))

print("\nComparison of V2 Rule-Based vs. V2 Semantic Retrieval Success Rates:")
comparison_df = final_comparison_summary_final[[
    'category_names',
    'predicted_category_v2_success_rate',
    'predicted_category_semantic_success_rate',
    'total_clips'
]].sort_values(by='total_clips', ascending=False).round(2)
display(comparison_df)

overall_v2_rule_based = final_comparison_summary_final[final_comparison_summary_final['category_names'] == 'Overall']['predicted_category_v2_success_rate'].iloc[0]
overall_v2_semantic = final_comparison_summary_final[final_comparison_summary_final['category_names'] == 'Overall']['predicted_category_semantic_success_rate'].iloc[0]

if overall_v2_rule_based == overall_v2_semantic:
    print(f"\nVerdict: The overall success rates for V2 rule-based ({overall_v2_rule_based:.2f}%) and V2 semantic retrieval ({overall_v2_semantic:.2f}%) are the same.")
else:
    print(f"\nVerdict: The overall success rates for V2 rule-based ({overall_v2_rule_based:.2f}%) and V2 semantic retrieval ({overall_v2_semantic:.2f}%) are different. Semantic retrieval has a higher success rate.")

Combined Category-wise Success Rates and Total Clips (with Overall Summary):


,category_names,predicted_category_v1_success_rate,predicted_category_v2_success_rate,predicted_category_from_phrase_success_rate,total_clips_x,predicted_category_semantic_success_rate,total_clips_y,total_clips
20,Overall,28.73,60.48,91.14,NaN,66.522678,NaN,463.0
0,Black Plastic Containers,19.44,80.56,97.22,36.0,69.44%,36.0,NaN
1,Black Plastic Containers | Other Unnumbered Co...,0.00,0.00,0.00,1.0,100.00%,1.0,NaN
2,Containers #1/Clamshells,22.54,64.79,91.55,71.0,80.28%,71.0,NaN
3,Containers #1/Clamshells | Garbage Bags,0.00,0.00,0.00,1.0,100.00%,1.0,NaN
4,Containers #2 Colored,26.32,73.68,94.74,19.0,63.16%,19.0,NaN
5,Containers #2 Colored | Deposit #1 Bottles,0.00,0.00,0.00,1.0,100.00%,1.0,NaN
6,Containers #2 Colored | Other #1 Bottles,0.00,0.00,0.00,2.0,50.00%,2.0,NaN
7,Containers #2 Natural,18.75,6.25,75.00,16.0,62.50%,16.0,NaN
8,Containers #3-7 (Not #5),61.54,53.85,100.00,13.0,76.92%,13.0,NaN



Comparison of V2 Rule-Based vs. V2 Semantic Retrieval Success Rates:


,category_names,predicted_category_v2_success_rate,predicted_category_semantic_success_rate,total_clips
20,Overall,60.48,66.522678,463.0
0,Black Plastic Containers,80.56,69.44%,NaN
1,Black Plastic Containers | Other Unnumbered Co...,0.00,100.00%,NaN
2,Containers #1/Clamshells,64.79,80.28%,NaN
3,Containers #1/Clamshells | Garbage Bags,0.00,100.00%,NaN
4,Containers #2 Colored,73.68,63.16%,NaN
5,Containers #2 Colored | Deposit #1 Bottles,0.00,100.00%,NaN
6,Containers #2 Colored | Other #1 Bottles,0.00,50.00%,NaN
7,Containers #2 Natural,6.25,62.50%,NaN
8,Containers #3-7 (Not #5),53.85,76.92%,NaN



Verdict: The overall success rates for V2 rule-based (60.48%) and V2 semantic retrieval (66.52%) are different. Semantic retrieval has a higher success rate.


### Summary of Comparison

Based on the table, we can observe the following:

*   **`meta2_phrase` (Ground Truth Phrase Mapping):** Achieves the highest overall success rate (**91.14%**). This serves as an upper bound for the `map_transcript_to_category` function, indicating how well the rule-based mapping performs when given the exact `meta2_phrase`.

*   **V2 (Whisper Large) with Rule-Based Mapping:** Shows a significantly better overall success rate (**60.48%**) compared to V1 when using the `map_transcript_to_category` function. This suggests that the 'large' Whisper model provides more accurate transcriptions that align better with the rule-based categorization logic.

*   **V1 (Whisper Base) with Rule-Based Mapping:** Has the lowest overall success rate (**28.73%**), indicating that the 'base' model's transcriptions are less suitable for direct application with the current rule-based `map_transcript_to_category` function.

*   **V2 (Whisper Large) with Semantic Retrieval:** Achieved an overall success rate of **66.52%**. This method slightly outperforms the rule-based mapping with V2 transcriptions, suggesting that leveraging semantic understanding can be beneficial, especially for transcriptions that might not exactly match predefined keywords but are semantically related.

### Semantic Retrieval for V1 Transcriptions and `meta2_phrase`

In [ ]:
# Apply semantic retrieval to V1 transcriptions
print("Applying semantic retrieval to V1 transcriptions...")
final_comparison_df_v1['predicted_category_semantic'] = final_comparison_df_v1['transcription_text_snippet'].apply(get_semantic_category)
semantic_success_rate_v1 = (final_comparison_df_v1['predicted_category_semantic'] == final_comparison_df_v1['category_names']).mean() * 100
print(f"V1 (Base) Semantic Retrieval success rate: {semantic_success_rate_v1:.2f}%")

# Apply semantic retrieval to original meta2_phrase
print("\nApplying semantic retrieval to meta2_phrase (ground truth)...")
timestamp_groups_df['predicted_category_semantic'] = timestamp_groups_df['meta2_phrase'].apply(get_semantic_category)
semantic_success_rate_from_phrase = (timestamp_groups_df['predicted_category_semantic'] == timestamp_groups_df['category_names']).mean() * 100
print(f"Meta2_phrase Semantic Retrieval success rate: {semantic_success_rate_from_phrase:.2f}%")

Applying semantic retrieval to V1 transcriptions...


NameError: name 'final_comparison_df_v1' is not defined

In [ ]:
# Calculate category-wise semantic success rates for V1
match_by_category_semantic_v1 = final_comparison_df_v1.groupby('category_names')['predicted_category_semantic'].apply(
    lambda x: (x == final_comparison_df_v1.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')

# Calculate category-wise semantic success rates for meta2_phrase
match_by_category_semantic_from_phrase = timestamp_groups_df.groupby('category_names')['predicted_category_semantic'].apply(
    lambda x: (x == timestamp_groups_df.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')

# Merge new semantic success rates into the comparison summary

# First, merge V1 semantic rates
final_comparison_summary_temp = pd.merge(
    final_comparison_summary_final.drop(columns=['predicted_category_semantic_success_rate', 'total_clips']) if 'predicted_category_semantic_success_rate' in final_comparison_summary_final.columns else final_comparison_summary_final.copy(), # Drop existing semantic column if present to avoid duplication or type issues
    match_by_category_semantic_v1.rename('predicted_category_semantic_v1_success_rate').reset_index(),
    on='category_names',
    how='left'
)

# Then, merge meta2_phrase semantic rates
final_comparison_summary_temp = pd.merge(
    final_comparison_summary_temp,
    match_by_category_semantic_from_phrase.rename('predicted_category_semantic_from_phrase_success_rate').reset_index(),
    on='category_names',
    how='left'
)

# Finally, re-merge the existing V2 semantic rates (which are already in final_comparison_summary_final) and total_clips
# Ensure total_clips is included by re-merging with total_clips_by_category if necessary
if 'total_clips' not in final_comparison_summary_temp.columns:
    final_comparison_summary_temp = pd.merge(
        final_comparison_summary_temp,
        total_clips_by_category,
        on='category_names',
        how='outer'
    )

# Add the V2 semantic rates back from the last computation, using the 'final_comparison_summary_final' as the source for 'predicted_category_semantic_success_rate'
final_comparison_summary_final_updated = pd.merge(
    final_comparison_summary_temp,
    final_comparison_summary_final[['category_names', 'predicted_category_semantic_success_rate']],
    on='category_names',
    how='left' # Use left to keep category_names from temp which might have 'Overall' row
)

# Update overall row for V1 and meta2_phrase semantic success rates
overall_index = final_comparison_summary_final_updated[final_comparison_summary_final_updated['category_names'] == 'Overall'].index
if not overall_index.empty:
    idx = overall_index[0]
    final_comparison_summary_final_updated.loc[idx, 'predicted_category_semantic_v1_success_rate'] = semantic_success_rate_v1
    final_comparison_summary_final_updated.loc[idx, 'predicted_category_semantic_from_phrase_success_rate'] = semantic_success_rate_from_phrase
else:
    # If 'Overall' row doesn't exist, create it with all data
    overall_summary_row_new = pd.DataFrame([{
        'category_names': 'Overall',
        'predicted_category_v1_success_rate': overall_success_v1,
        'predicted_category_v2_success_rate': overall_success_v2,
        'predicted_category_from_phrase_success_rate': overall_success_from_phrase,
        'predicted_category_semantic_success_rate': semantic_success_rate_v2,
        'predicted_category_semantic_v1_success_rate': semantic_success_rate_v1,
        'predicted_category_semantic_from_phrase_success_rate': semantic_success_rate_from_phrase,
        'total_clips': overall_total_clips
    }])
    final_comparison_summary_final_updated = pd.concat([final_comparison_summary_final_updated, overall_summary_row_new], ignore_index=True)

# Display the final comparison summary with all metrics
print("\nCombined Category-wise Success Rates and Total Clips (with ALL Semantic Summaries):")
display(final_comparison_summary_final_updated.sort_values(by='total_clips', ascending=False).round(2))

NameError: name 'final_comparison_df_v1' is not defined

### Re-computing Semantic Retrieval for V1 and `meta2_phrase` with full context

In [ ]:
import pandas as pd
import os
import json
from tqdm.notebook import tqdm
from sentence_transformers import SentenceTransformer, util
import numpy as np

# --- Re-initialize essential global variables ---
# Assuming db_root is set, if not, it should be set here too.
# db_root = 'drive/MyDrive/camera1_plastics_shareable_dataset'

# --- Load/reconstruct timestamp_groups_df ---
timestamp_groups_csv_path = f'{db_root}/camera1_plastics_timestamp_groups.csv'
try:
    timestamp_groups_df = pd.read_csv(timestamp_groups_csv_path)
    timestamp_groups_df['clip_id'] = timestamp_groups_df['clip_path'].apply(lambda x: os.path.splitext(os.path.basename(x))[0] if pd.notna(x) else None)
except Exception as e:
    print(f"Error loading timestamp_groups_df: {e}")
    timestamp_groups_df = pd.DataFrame()

# --- Reconstruct final_comparison_df_v1 (for V1 transcriptions) ---
transcribe_output_dir_v1 = '/content/drive/MyDrive/csire_code/transcribe/v1'
audio_input_dir = '/content/drive/MyDrive/csire_code/audio'

# Reconstruct V1 transcription results
transcription_results_v1 = []
for txt_filename in tqdm(os.listdir(transcribe_output_dir_v1), desc="Reconstructing V1 Transcriptions"):
    if txt_filename.endswith('.txt'):
        audio_filename = txt_filename.replace('.txt', '.mp3')
        audio_path = os.path.join(audio_input_dir, audio_filename)
        transcription_path = os.path.join(transcribe_output_dir_v1, txt_filename)
        try:
            with open(transcription_path, 'r', encoding='utf-8') as f:
                transcription_text = f.read()
            transcription_results_v1.append({
                'audio_filename': audio_filename,
                'audio_path': audio_path,
                'transcription_path': transcription_path,
                'status': 'success',
                'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
            })
        except Exception as e:
            print(f"Error reading V1 transcription file {txt_filename}: {e}")
transcription_df_v1 = pd.DataFrame(transcription_results_v1)
transcription_df_v1['clip_id'] = transcription_df_v1['audio_filename'].apply(lambda x: os.path.splitext(x)[0])

final_comparison_df_v1 = pd.merge(
    transcription_df_v1,
    timestamp_groups_df[['clip_id', 'meta2_phrase', 'category_names', 'supercategory_names', 'begin_time', 'end_time']].rename(columns={
        'meta2_phrase': 'phrase',
        'supercategory_names': 'supercategory_name'
    }),
    left_on='clip_id',
    right_on='clip_id',
    how='left'
)

# --- Reconstruct final_comparison_df_v2 (for V2 transcriptions) ---
transcribe_output_dir_v2 = '/content/drive/MyDrive/csire_code/transcribe/v2'

# Reconstruct V2 transcription results
transcription_results_v2 = []
for txt_filename in tqdm(os.listdir(transcribe_output_dir_v2), desc="Reconstructing V2 Transcriptions"):
    if txt_filename.endswith('.txt'):
        audio_filename = txt_filename.replace('.txt', '.mp3')
        audio_path = os.path.join(audio_input_dir, audio_filename)
        transcription_path = os.path.join(transcribe_output_dir_v2, txt_filename)
        try:
            with open(transcription_path, 'r', encoding='utf-8') as f:
                transcription_text = f.read()
            transcription_results_v2.append({
                'audio_filename': audio_filename,
                'audio_path': audio_path,
                'transcription_path': transcription_path,
                'status': 'success',
                'transcription_text_snippet': transcription_text[:100] + '...' if len(transcription_text) > 100 else transcription_text
            })
        except Exception as e:
            print(f"Error reading V2 transcription file {txt_filename}: {e}")
transcription_df_v2 = pd.DataFrame(transcription_results_v2)
transcription_df_v2['clip_id'] = transcription_df_v2['audio_filename'].apply(lambda x: os.path.splitext(x)[0])

final_comparison_df_v2 = pd.merge(
    transcription_df_v2,
    timestamp_groups_df[['clip_id', 'meta2_phrase', 'category_names', 'supercategory_names', 'begin_time', 'end_time']].rename(columns={
        'meta2_phrase': 'phrase',
        'supercategory_names': 'supercategory_name'
    }),
    left_on='clip_id',
    right_on='clip_id',
    how='left'
)

# --- Load common phrases for semantic retrieval ---
common_phrases_csv_path = f'{db_root}/camera1_plastics_common_phrases.csv'
try:
    common_phrases_df = pd.read_csv(common_phrases_csv_path)
    if 'example_categories' in common_phrases_df.columns:
        common_phrases_df['parsed_categories'] = common_phrases_df['example_categories'].apply(
            lambda x: json.loads(x.replace("'", '"')) if isinstance(x, str) and x.startswith('[') else x
        )
        common_phrases_df['target_category'] = common_phrases_df['parsed_categories'].apply(
            lambda x: x[0] if isinstance(x, list) and x else (x if x is not None else None)
        )
    common_phrases_df.dropna(subset=['normalized_phrase', 'target_category'], inplace=True)
except Exception as e:
    print(f"Error loading common_phrases_df: {e}")
    common_phrases_df = pd.DataFrame()

# --- Load Sentence Transformer Model and Generate Embeddings ---
print("Loading Sentence Transformer model...")
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
print("Sentence Transformer model loaded.")

print("Generating embeddings for common phrases...")
common_phrase_embeddings = embedding_model.encode(common_phrases_df['normalized_phrase'].tolist(), convert_to_tensor=True)

# --- Define get_semantic_category function ---
def get_semantic_category(transcript_text, top_k=1):
    if pd.isna(transcript_text) or not isinstance(transcript_text, str):
        return "Unknown"

    transcript_embedding = embedding_model.encode(transcript_text, convert_to_tensor=True)
    cosine_scores = util.cos_sim(transcript_embedding, common_phrase_embeddings)[0]
    top_results = np.argpartition(-cosine_scores.cpu().numpy(), top_k)[:top_k]

    if len(top_results) > 0:
        best_match_idx = top_results[0]
        return common_phrases_df.iloc[best_match_idx]['target_category']
    else:
        return "Unknown"

# --- Apply semantic retrieval to V1 transcriptions ---
print("\nApplying semantic retrieval to V1 transcriptions...")
final_comparison_df_v1['predicted_category_semantic'] = final_comparison_df_v1['transcription_text_snippet'].apply(get_semantic_category)
semantic_success_rate_v1 = (final_comparison_df_v1['predicted_category_semantic'] == final_comparison_df_v1['category_names']).mean() * 100
print(f"V1 (Base) Semantic Retrieval success rate: {semantic_success_rate_v1:.2f}%")

# --- Apply semantic retrieval to original meta2_phrase ---
print("\nApplying semantic retrieval to meta2_phrase (ground truth)...")
# Create a copy to avoid SettingWithCopyWarning if timestamp_groups_df is a slice
timestamp_groups_df_copy = timestamp_groups_df.copy()
timestamp_groups_df_copy['predicted_category_semantic'] = timestamp_groups_df_copy['meta2_phrase'].apply(get_semantic_category)
semantic_success_rate_from_phrase = (timestamp_groups_df_copy['predicted_category_semantic'] == timestamp_groups_df_copy['category_names']).mean() * 100
print(f"Meta2_phrase Semantic Retrieval success rate: {semantic_success_rate_from_phrase:.2f}%")

# --- Recompute semantic_success_rate_v2 for consistency ---
# This was previously computed, but re-calculating ensures it's fresh in this run.
final_comparison_df_v2['predicted_category_semantic'] = final_comparison_df_v2['transcription_text_snippet'].apply(get_semantic_category)
semantic_success_rate_v2 = (final_comparison_df_v2['predicted_category_semantic'] == final_comparison_df_v2['category_names']).mean() * 100

# --- Calculate category-wise semantic success rates ---
match_by_category_semantic_v1 = final_comparison_df_v1.groupby('category_names')['predicted_category_semantic'].apply(
    lambda x: (x == final_comparison_df_v1.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')

match_by_category_semantic_from_phrase = timestamp_groups_df_copy.groupby('category_names')['predicted_category_semantic'].apply(
    lambda x: (x == timestamp_groups_df_copy.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')

match_by_category_semantic_v2 = final_comparison_df_v2.groupby('category_names')['predicted_category_semantic'].apply(
    lambda x: (x == final_comparison_df_v2.loc[x.index, 'category_names']).mean() * 100
).apply(lambda x: f'{x:.2f}%')

# --- Re-generate final_comparison_summary_final with ALL metrics ---
# Re-obtain overall rule-based success rates
def map_transcript_to_category(transcript_text):
    if pd.isna(transcript_text): return "Unknown"
    text = transcript_text.lower()
    if text == "non -deposit garbage bag": return "Non-Deposit"
    if text == "dissolt.": return "Deposit #1 Bottles"
    if text == "fly plastic.": return "Black Plastic Containers"
    if text == "under posit one down to positive": return "Non-Deposit"
    if text == "no." or text == "no": return "Containers #1/Clamshells"
    if text == "one deposit." or text == "one deposit": return "Deposit #1 Bottles"
    if "other one" in text or "lid" in text: return "Containers #1/Clamshells"
    if "five" in text or "5" in text: return "Containers #5/PP"
    if text == "unnumbered.": return "Other Unnumbered Containers & Fragments"
    if text == "other plastic.": return "Other Plastics"
    if "two" in text and "color" in text: return "Containers #2 Colored"
    if text == "number one.": return "Deposit #1 Bottles"
    if ("one" in text or "1" in text) and "non" in text: return "Other #1 Bottles"
    if "non" in text and "deposit" in text: return "Non-Deposit"
    if "garbage bag" in text: return "Garbage Bags"
    if "black" in text: return "Black Plastic Containers"
    if "clam" in text and "shell" in text: return "Containers #1/Clamshells"
    if "two natural" in text: return "Containers #2 Natural"
    if "two color" in text or "two colored" in text: return "Containers #2 Colored"
    if "three" in text or "3" in text or "seven" in text or "7" in text or "four" in text or "4" in text or "six" in text or "6" in text: return "Containers #3-7 (Not #5)"
    if "five" in text or "5" in text: return "Containers #5/PP"
    if "number one" in text:
        if "deposit" in text: return "Deposit #1 Bottles"
        return "Other #1 Bottles"
    if "deposit" in text: return "Deposit #1 Bottles"
    if "plastic film" in text or "film plastic" in text or "film" in text: return "Other Plastic Film"
    if "other plastic" in text: return "Other Plastics"
    if "unnumbered" in text: return "Other Unnumbered Containers & Fragments"
    if "bulky rigid" in text: return "Other Rigid/Bulky Plastics"
    if "if you find numbers" in text: return "Other Unnumbered Containers & Fragments"
    if "plastic" in text: return "Plastic"
    if "one" in text: return "Containers #1/Clamshells"
    return "Unknown"

final_comparison_df_v1['predicted_category'] = final_comparison_df_v1['transcription_text_snippet'].apply(map_transcript_to_category)
overall_success_v1 = (final_comparison_df_v1['predicted_category'] == final_comparison_df_v1['category_names']).mean() * 100

final_comparison_df_v2['predicted_category'] = final_comparison_df_v2['transcription_text_snippet'].apply(map_transcript_to_category)
overall_success_v2 = (final_comparison_df_v2['predicted_category'] == final_comparison_df_v2['category_names']).mean() * 100

timestamp_groups_df_copy['predicted_category_from_phrase'] = timestamp_groups_df_copy['meta2_phrase'].apply(map_transcript_to_category)
overall_success_from_phrase = (timestamp_groups_df_copy['predicted_category_from_phrase'] == timestamp_groups_df_copy['category_names']).mean() * 100

# Calculate success rates for V1 by category_name (rule-based)
success_by_category_v1 = final_comparison_df_v1.groupby('category_names')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v1.loc[x.index, 'category_names']).mean() * 100
).reset_index()
success_by_category_v1.rename(columns={'predicted_category': 'predicted_category_v1_success_rate'}, inplace=True)

# Calculate success rates for V2 by category_name (rule-based)
suc_by_cat_v2 = final_comparison_df_v2.groupby('category_names')['predicted_category'].apply(
    lambda x: (x == final_comparison_df_v2.loc[x.index, 'category_names']).mean() * 100
).reset_index()
suc_by_cat_v2.rename(columns={'predicted_category': 'predicted_category_v2_success_rate'}, inplace=True)

# Calculate success rates for 'predicted_category_from_phrase' (rule-based ground truth phrase mapping) using timestamp_groups_df
suc_by_cat_from_phrase = timestamp_groups_df_copy.groupby('category_names')['predicted_category_from_phrase'].apply(
    lambda x: (x == timestamp_groups_df_copy.loc[x.index, 'category_names']).mean() * 100
).reset_index()
suc_by_cat_from_phrase.rename(columns={'predicted_category_from_phrase': 'predicted_category_from_phrase_success_rate'}, inplace=True)

# Merge all rule-based success rates into a single DataFrame
comparison_success_rates_rule_based = pd.merge(success_by_category_v1, suc_by_cat_v2, on='category_names', how='outer')
comparison_success_rates_rule_based = pd.merge(comparison_success_rates_rule_based, suc_by_cat_from_phrase, on='category_names', how='outer')

# Total clips by category
total_clips_by_category = timestamp_groups_df_copy.groupby('category_names')['clip_id'].nunique().reset_index()
total_clips_by_category.rename(columns={'clip_id': 'total_clips'}, inplace=True)
overall_total_clips = total_clips_by_category['total_clips'].sum()

# Merge rule-based success rates with semantic success rates
final_comparison_summary_final = pd.merge(comparison_success_rates_rule_based,
                                          match_by_category_semantic_v1.rename('predicted_category_semantic_v1_success_rate').reset_index(),
                                          on='category_names', how='outer')
final_comparison_summary_final = pd.merge(final_comparison_summary_final,
                                          match_by_category_semantic_v2.rename('predicted_category_semantic_success_rate').reset_index(),
                                          on='category_names', how='outer')
final_comparison_summary_final = pd.merge(final_comparison_summary_final,
                                          match_by_category_semantic_from_phrase.rename('predicted_category_semantic_from_phrase_success_rate').reset_index(),
                                          on='category_names', how='outer')
final_comparison_summary_final = pd.merge(final_comparison_summary_final, total_clips_by_category, on='category_names', how='outer')

# Add the overall row
overall_summary_row = pd.DataFrame([
    {
        'category_names': 'Overall',
        'predicted_category_v1_success_rate': overall_success_v1,
        'predicted_category_v2_success_rate': overall_success_v2,
        'predicted_category_from_phrase_success_rate': overall_success_from_phrase,
        'predicted_category_semantic_v1_success_rate': semantic_success_rate_v1,
        'predicted_category_semantic_success_rate': semantic_success_rate_v2,
        'predicted_category_semantic_from_phrase_success_rate': semantic_success_rate_from_phrase,
        'total_clips': overall_total_clips
    }
])

final_comparison_summary_final_updated = pd.concat([final_comparison_summary_final, overall_summary_row], ignore_index=True)


print("\nCombined Category-wise Success Rates and Total Clips (with ALL Semantic Summaries):")
display(final_comparison_summary_final_updated.sort_values(by='total_clips', ascending=False).round(2))


Reconstructing V1 Transcriptions:   0%|          | 0/463 [00:00<?, ?it/s]

Reconstructing V2 Transcriptions:   0%|          | 0/463 [00:00<?, ?it/s]

Loading Sentence Transformer model...


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Sentence Transformer model loaded.
Generating embeddings for common phrases...

Applying semantic retrieval to V1 transcriptions...
V1 (Base) Semantic Retrieval success rate: 39.31%

Applying semantic retrieval to meta2_phrase (ground truth)...
Meta2_phrase Semantic Retrieval success rate: 97.84%

Combined Category-wise Success Rates and Total Clips (with ALL Semantic Summaries):


,category_names,predicted_category_v1_success_rate,predicted_category_v2_success_rate,predicted_category_from_phrase_success_rate,predicted_category_semantic_v1_success_rate,predicted_category_semantic_success_rate,predicted_category_semantic_from_phrase_success_rate,total_clips
20,Overall,28.73,60.48,91.14,39.308855,66.522678,97.840173,463
13,Other #1 Bottles,22.22,56.79,88.89,18.52%,60.49%,93.83%,81
2,Containers #1/Clamshells,22.54,64.79,91.55,49.30%,80.28%,100.00%,71
9,Containers #5/PP,60.71,85.71,100.00,50.00%,66.07%,100.00%,56
10,Deposit #1 Bottles,30.91,69.09,92.73,38.18%,69.09%,94.55%,55
18,Other Unnumbered Containers & Fragments,36.96,71.74,91.30,65.22%,82.61%,100.00%,46
16,Other Plastics,19.44,38.89,100.00,30.56%,52.78%,100.00%,36
0,Black Plastic Containers,19.44,80.56,97.22,27.78%,69.44%,97.22%,36
4,Containers #2 Colored,26.32,73.68,94.74,52.63%,63.16%,100.00%,19
12,Non-Deposit,5.56,5.56,88.89,11.11%,22.22%,100.00%,18
